// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api.sql

package sqlc

import (
	"context"
	"time"
)

const countRegressions = `-- name: CountRegressions :one
SELECT count(*) FROM issues WHERE project_id = $1 AND status = 'regression' AND last_seen >= $2
`

type CountRegressionsParams struct {
	ProjectID int64     `json:"project_id"`
	LastSeen  time.Time `json:"last_seen"`
}

// Issues currently in 'regression' that were seen in the window.
func (q *Queries) CountRegressions(ctx context.Context, arg CountRegressionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRegressions, arg.ProjectID, arg.LastSeen)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegressionsIn = `-- name: CountRegressionsIn :one
SELECT count(*) FROM issues WHERE project_id = $1 AND status = 'regression' AND last_seen >= $2 AND last_seen < $3
`

type CountRegressionsInParams struct {
	ProjectID int64     `json:"project_id"`
	FromAt    time.Time `json:"from_at"`
	ToAt      time.Time `json:"to_at"`
}

// Issues currently in 'regression' that were seen in [from, to).
func (q *Queries) CountRegressionsIn(ctx context.Context, arg CountRegressionsInParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRegressionsIn, arg.ProjectID, arg.FromAt, arg.ToAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const newIssuesByRelease = `-- name: NewIssuesByRelease :many

SELECT first_release AS release, count(*)::bigint AS n
FROM issues
WHERE project_id = $1 AND first_seen >= $2 AND first_seen < $3 AND first_release IS NOT NULL
GROUP BY first_release
`

type NewIssuesByReleaseParams struct {
	ProjectID   int64     `json:"project_id"`
	FirstSeen   time.Time `json:"first_seen"`
	FirstSeen_2 time.Time `json:"first_seen_2"`
}

type NewIssuesByReleaseRow struct {
	Release *string `json:"release"`
	N       int64   `json:"n"`
}

// Queries used only by internal/api.
// Issues first seen in the window, grouped by the release that introduced them.
func (q *Queries) NewIssuesByRelease(ctx context.Context, arg NewIssuesByReleaseParams) ([]NewIssuesByReleaseRow, error) {
	rows, err := q.db.Query(ctx, newIssuesByRelease, arg.ProjectID, arg.FirstSeen, arg.FirstSeen_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewIssuesByReleaseRow{}
	for rows.Next() {
		var i NewIssuesByReleaseRow
		if err := rows.Scan(&i.Release, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
