// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/at-least/crashcart/internal/sentry"
)

const getAttachment = `-- name: GetAttachment :one
SELECT occurred_at, project_id, event_id, n, filename, content_type, attachment_type, size, data FROM attachments WHERE project_id = $1 AND event_id = $2 AND occurred_at = $3 AND n = $4
`

type GetAttachmentParams struct {
	ProjectID  int64     `json:"project_id"`
	EventID    sentry.ID `json:"event_id"`
	OccurredAt time.Time `json:"occurred_at"`
	N          int32     `json:"n"`
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment,
		arg.ProjectID,
		arg.EventID,
		arg.OccurredAt,
		arg.N,
	)
	var i Attachment
	err := row.Scan(
		&i.OccurredAt,
		&i.ProjectID,
		&i.EventID,
		&i.N,
		&i.Filename,
		&i.ContentType,
		&i.AttachmentType,
		&i.Size,
		&i.Data,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many

SELECT occurred_at, project_id, event_id, n, filename, content_type, attachment_type, size
FROM attachments WHERE project_id = $1 AND event_id = $2 AND occurred_at = $3 ORDER BY n
`

type ListAttachmentsParams struct {
	ProjectID  int64     `json:"project_id"`
	EventID    sentry.ID `json:"event_id"`
	OccurredAt time.Time `json:"occurred_at"`
}

type ListAttachmentsRow struct {
	OccurredAt     time.Time `json:"occurred_at"`
	ProjectID      int64     `json:"project_id"`
	EventID        sentry.ID `json:"event_id"`
	N              int32     `json:"n"`
	Filename       string    `json:"filename"`
	ContentType    string    `json:"content_type"`
	AttachmentType string    `json:"attachment_type"`
	Size           int64     `json:"size"`
}

// Attachment writes are pipelined by store.InsertAttachments (hand-written).
// An event's attachments without their bytes (the event page, the API).
// The time keeps the lookup to one partition.
func (q *Queries) ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, arg.ProjectID, arg.EventID, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsRow{}
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.OccurredAt,
			&i.ProjectID,
			&i.EventID,
			&i.N,
			&i.Filename,
			&i.ContentType,
			&i.AttachmentType,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
