// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chunks.sql

package sqlc

import (
	"context"
	"time"
)

const deleteUploadChunks = `-- name: DeleteUploadChunks :exec
DELETE FROM upload_chunks WHERE sha1 = ANY($1::text[])
`

func (q *Queries) DeleteUploadChunks(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteUploadChunks, dollar_1)
	return err
}

const expireUploadChunks = `-- name: ExpireUploadChunks :execrows
DELETE FROM upload_chunks WHERE created_at < $1
`

func (q *Queries) ExpireUploadChunks(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expireUploadChunks, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUploadChunks = `-- name: GetUploadChunks :many
SELECT c.sha1, c.data FROM unnest($1::text[]) WITH ORDINALITY AS w(sha1, n)
JOIN upload_chunks c ON c.sha1 = w.sha1 ORDER BY w.n
`

type GetUploadChunksRow struct {
	Sha1 string `json:"sha1"`
	Data []byte `json:"data"`
}

// The chunks of one file, in the order the assemble request lists them.
func (q *Queries) GetUploadChunks(ctx context.Context, sha1s []string) ([]GetUploadChunksRow, error) {
	rows, err := q.db.Query(ctx, getUploadChunks, sha1s)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUploadChunksRow{}
	for rows.Next() {
		var i GetUploadChunksRow
		if err := rows.Scan(&i.Sha1, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putUploadChunk = `-- name: PutUploadChunk :exec
INSERT INTO upload_chunks (sha1, data) VALUES ($1, $2) ON CONFLICT (sha1) DO NOTHING
`

type PutUploadChunkParams struct {
	Sha1 string `json:"sha1"`
	Data []byte `json:"data"`
}

func (q *Queries) PutUploadChunk(ctx context.Context, arg PutUploadChunkParams) error {
	_, err := q.db.Exec(ctx, putUploadChunk, arg.Sha1, arg.Data)
	return err
}

const uploadChunksPresent = `-- name: UploadChunksPresent :many
SELECT sha1 FROM upload_chunks WHERE sha1 = ANY($1::text[])
`

func (q *Queries) UploadChunksPresent(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, uploadChunksPresent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var sha1 string
		if err := rows.Scan(&sha1); err != nil {
			return nil, err
		}
		items = append(items, sha1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
