// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertEvents implements pgx.CopyFromSource.
type iteratorForInsertEvents struct {
	rows                 []InsertEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].EventID,
		r.rows[0].Level,
		r.rows[0].Message,
		r.rows[0].Platform,
		r.rows[0].Environment,
		r.rows[0].Release,
		r.rows[0].DeviceID,
		r.rows[0].DeviceModel,
		r.rows[0].OsVersion,
		r.rows[0].Screen,
		r.rows[0].ErrorType,
		r.rows[0].ErrorLocation,
		r.rows[0].Handled,
		r.rows[0].SdkName,
		r.rows[0].UserID,
		r.rows[0].Fingerprint,
		r.rows[0].Tags,
		r.rows[0].Breadcrumbs,
		r.rows[0].Payload,
	}, nil
}

func (r iteratorForInsertEvents) Err() error {
	return nil
}

// events.id encodes the event time (internal/pk); every query below bounds
// the scan with an id range so it walks the PK — the table's only index.
func (q *Queries) InsertEvents(ctx context.Context, arg []InsertEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"events"}, []string{"id", "event_id", "level", "message", "platform", "environment", "release", "device_id", "device_model", "os_version", "screen", "error_type", "error_location", "handled", "sdk_name", "user_id", "fingerprint", "tags", "breadcrumbs", "payload"}, &iteratorForInsertEvents{rows: arg})
}
