// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getEvent = `-- name: GetEvent :one
SELECT id, project_id, event_id, level, message, platform, environment, release, device_id, device_model, os_version, screen, error_type, error_location, handled, sdk_name, user_id, fingerprint, symbolicated, tags, breadcrumbs, payload, symbols FROM events WHERE project_id = $1 AND id = $2
`

type GetEventParams struct {
	ProjectID int64 `json:"project_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, arg.ProjectID, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventID,
		&i.Level,
		&i.Message,
		&i.Platform,
		&i.Environment,
		&i.Release,
		&i.DeviceID,
		&i.DeviceModel,
		&i.OsVersion,
		&i.Screen,
		&i.ErrorType,
		&i.ErrorLocation,
		&i.Handled,
		&i.SdkName,
		&i.UserID,
		&i.Fingerprint,
		&i.Symbolicated,
		&i.Tags,
		&i.Breadcrumbs,
		&i.Payload,
		&i.Symbols,
	)
	return i, err
}

const getEventByEventID = `-- name: GetEventByEventID :one
SELECT id, project_id, event_id, level, message, platform, environment, release, device_id, device_model, os_version, screen, error_type, error_location, handled, sdk_name, user_id, fingerprint, symbolicated, tags, breadcrumbs, payload, symbols FROM events WHERE project_id = $1 AND event_id = $2 ORDER BY id DESC LIMIT 1
`

type GetEventByEventIDParams struct {
	ProjectID int64  `json:"project_id"`
	EventID   string `json:"event_id"`
}

func (q *Queries) GetEventByEventID(ctx context.Context, arg GetEventByEventIDParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByEventID, arg.ProjectID, arg.EventID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EventID,
		&i.Level,
		&i.Message,
		&i.Platform,
		&i.Environment,
		&i.Release,
		&i.DeviceID,
		&i.DeviceModel,
		&i.OsVersion,
		&i.Screen,
		&i.ErrorType,
		&i.ErrorLocation,
		&i.Handled,
		&i.SdkName,
		&i.UserID,
		&i.Fingerprint,
		&i.Symbolicated,
		&i.Tags,
		&i.Breadcrumbs,
		&i.Payload,
		&i.Symbols,
	)
	return i, err
}

const issueNeighbors = `-- name: IssueNeighbors :one
SELECT max(id)::bigint AS latest, min(id)::bigint AS oldest FROM events WHERE project_id = $1 AND fingerprint = $2
`

type IssueNeighborsParams struct {
	ProjectID   int64   `json:"project_id"`
	Fingerprint *string `json:"fingerprint"`
}

type IssueNeighborsRow struct {
	Latest int64 `json:"latest"`
	Oldest int64 `json:"oldest"`
}

// Latest and oldest stored event of an issue.
func (q *Queries) IssueNeighbors(ctx context.Context, arg IssueNeighborsParams) (IssueNeighborsRow, error) {
	row := q.db.QueryRow(ctx, issueNeighbors, arg.ProjectID, arg.Fingerprint)
	var i IssueNeighborsRow
	err := row.Scan(&i.Latest, &i.Oldest)
	return i, err
}

const issueUsers = `-- name: IssueUsers :many
SELECT fingerprint, count(DISTINCT user_id)::bigint AS users
FROM events WHERE project_id = $1 AND fingerprint = ANY($2::text[]) AND id >= $3 AND id < $4 AND user_id IS NOT NULL
GROUP BY fingerprint
`

type IssueUsersParams struct {
	ProjectID int64    `json:"project_id"`
	Column2   []string `json:"column_2"`
	ID        int64    `json:"id"`
	ID_2      int64    `json:"id_2"`
}

type IssueUsersRow struct {
	Fingerprint *string `json:"fingerprint"`
	Users       int64   `json:"users"`
}

// Distinct users per issue in a window (index: project_id, fingerprint, id).
func (q *Queries) IssueUsers(ctx context.Context, arg IssueUsersParams) ([]IssueUsersRow, error) {
	rows, err := q.db.Query(ctx, issueUsers,
		arg.ProjectID,
		arg.Column2,
		arg.ID,
		arg.ID_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueUsersRow{}
	for rows.Next() {
		var i IssueUsersRow
		if err := rows.Scan(&i.Fingerprint, &i.Users); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventSymbols = `-- name: SetEventSymbols :exec
UPDATE events SET symbols = $3, symbolicated = true, fingerprint = $4, error_location = $5
WHERE project_id = $1 AND id = $2
`

type SetEventSymbolsParams struct {
	ProjectID     int64           `json:"project_id"`
	ID            int64           `json:"id"`
	Symbols       json.RawMessage `json:"symbols"`
	Fingerprint   *string         `json:"fingerprint"`
	ErrorLocation *string         `json:"error_location"`
}

func (q *Queries) SetEventSymbols(ctx context.Context, arg SetEventSymbolsParams) error {
	_, err := q.db.Exec(ctx, setEventSymbols,
		arg.ProjectID,
		arg.ID,
		arg.Symbols,
		arg.Fingerprint,
		arg.ErrorLocation,
	)
	return err
}
