// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package sqlc

import (
	"context"
	"time"
)

const deleteIssuesBefore = `-- name: DeleteIssuesBefore :execrows
DELETE FROM issues WHERE last_seen < $1
`

func (q *Queries) DeleteIssuesBefore(ctx context.Context, lastSeen time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIssuesBefore, lastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIssue = `-- name: GetIssue :one
SELECT fingerprint, title, level, error_type, screen, platform, status, event_count, first_seen, last_seen, first_release, last_release, created_at, updated_at FROM issues WHERE fingerprint = $1
`

func (q *Queries) GetIssue(ctx context.Context, fingerprint string) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssue, fingerprint)
	var i Issue
	err := row.Scan(
		&i.Fingerprint,
		&i.Title,
		&i.Level,
		&i.ErrorType,
		&i.Screen,
		&i.Platform,
		&i.Status,
		&i.EventCount,
		&i.FirstSeen,
		&i.LastSeen,
		&i.FirstRelease,
		&i.LastRelease,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssues = `-- name: ListIssues :many
SELECT fingerprint, title, level, error_type, screen, platform, status, event_count, first_seen, last_seen, first_release, last_release, created_at, updated_at FROM issues i
WHERE i.last_seen >= $1
  AND ($2::timestamptz IS NULL OR i.first_seen < $2)
  AND ($3::text IS NULL OR i.error_type = $3)
  AND ($4::text IS NULL OR i.status = $4)
  AND (NOT $5::boolean OR i.fingerprint = ANY($6::text[]))
ORDER BY i.last_seen DESC
LIMIT $7
`

type ListIssuesParams struct {
	Since         time.Time  `json:"since"`
	Until         *time.Time `json:"until"`
	ErrorType     *string    `json:"error_type"`
	Status        *string    `json:"status"`
	ByFingerprint bool       `json:"by_fingerprint"`
	Fingerprints  []string   `json:"fingerprints"`
	PageLimit     int32      `json:"page_limit"`
}

// Optional filters. Event-scoped filtering (release/user/device/…) is done
// by the caller: FingerprintsInRange → @fingerprints (empty = no filter).
func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssues,
		arg.Since,
		arg.Until,
		arg.ErrorType,
		arg.Status,
		arg.ByFingerprint,
		arg.Fingerprints,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.Fingerprint,
			&i.Title,
			&i.Level,
			&i.ErrorType,
			&i.Screen,
			&i.Platform,
			&i.Status,
			&i.EventCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.FirstRelease,
			&i.LastRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newIssuesSince = `-- name: NewIssuesSince :many
SELECT fingerprint, title, error_type FROM issues
WHERE first_seen >= $1 AND level IN ('error', 'fatal')
ORDER BY first_seen DESC LIMIT 5
`

type NewIssuesSinceRow struct {
	Fingerprint string  `json:"fingerprint"`
	Title       string  `json:"title"`
	ErrorType   *string `json:"error_type"`
}

// Alerting: issues first seen since a point in time.
func (q *Queries) NewIssuesSince(ctx context.Context, firstSeen time.Time) ([]NewIssuesSinceRow, error) {
	rows, err := q.db.Query(ctx, newIssuesSince, firstSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewIssuesSinceRow{}
	for rows.Next() {
		var i NewIssuesSinceRow
		if err := rows.Scan(&i.Fingerprint, &i.Title, &i.ErrorType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regressionsSince = `-- name: RegressionsSince :many
SELECT fingerprint, title, error_type, last_release FROM issues
WHERE status = 'regression' AND last_seen >= $1
ORDER BY last_seen DESC LIMIT 5
`

type RegressionsSinceRow struct {
	Fingerprint string  `json:"fingerprint"`
	Title       string  `json:"title"`
	ErrorType   *string `json:"error_type"`
	LastRelease *string `json:"last_release"`
}

func (q *Queries) RegressionsSince(ctx context.Context, lastSeen time.Time) ([]RegressionsSinceRow, error) {
	rows, err := q.db.Query(ctx, regressionsSince, lastSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RegressionsSinceRow{}
	for rows.Next() {
		var i RegressionsSinceRow
		if err := rows.Scan(
			&i.Fingerprint,
			&i.Title,
			&i.ErrorType,
			&i.LastRelease,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueStatus = `-- name: UpdateIssueStatus :execrows
UPDATE issues SET status = $2, updated_at = now() WHERE fingerprint = $1
`

type UpdateIssueStatusParams struct {
	Fingerprint string `json:"fingerprint"`
	Status      string `json:"status"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIssueStatus, arg.Fingerprint, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
