// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const claimJobs = `-- name: ClaimJobs :many
UPDATE jobs SET locked_until = $1::timestamptz, attempts = attempts + 1
WHERE id IN (
    SELECT id FROM jobs
    WHERE run_after <= now() AND (locked_until IS NULL OR locked_until < now())
    ORDER BY run_after, id LIMIT $2::int FOR UPDATE SKIP LOCKED)
RETURNING id, kind, project_id, args, run_after, attempts, locked_until, last_error, created_at
`

type ClaimJobsParams struct {
	LockedUntil time.Time `json:"locked_until"`
	Max         int32     `json:"max"`
}

// Leases a batch (locked until $2) and counts the attempt. The caller runs
// the handlers outside any transaction, then deletes or reschedules each
// job; a lease that expires (worker died) makes the job claimable again.
func (q *Queries) ClaimJobs(ctx context.Context, arg ClaimJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, claimJobs, arg.LockedUntil, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ProjectID,
			&i.Args,
			&i.RunAfter,
			&i.Attempts,
			&i.LockedUntil,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countJobs = `-- name: CountJobs :one
SELECT count(*) FROM jobs
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :exec
INSERT INTO jobs (kind, project_id, args, run_after) VALUES ($1, $2, $3, $4)
`

type EnqueueJobParams struct {
	Kind      JobKind         `json:"kind"`
	ProjectID int64           `json:"project_id"`
	Args      json.RawMessage `json:"args"`
	RunAfter  time.Time       `json:"run_after"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) error {
	_, err := q.db.Exec(ctx, enqueueJob,
		arg.Kind,
		arg.ProjectID,
		arg.Args,
		arg.RunAfter,
	)
	return err
}

const enqueueJobs = `-- name: EnqueueJobs :exec
INSERT INTO jobs (kind, project_id, args, run_after)
SELECT unnest($1::text[])::job_kind, unnest($2::bigint[]), unnest($3::jsonb[]), unnest($4::timestamptz[])
`

type EnqueueJobsParams struct {
	Kinds      []string          `json:"kinds"`
	ProjectIds []int64           `json:"project_ids"`
	Args       []json.RawMessage `json:"args"`
	RunAfters  []time.Time       `json:"run_afters"`
}

// Multi-row insert: one statement, one NOTIFY.
func (q *Queries) EnqueueJobs(ctx context.Context, arg EnqueueJobsParams) error {
	_, err := q.db.Exec(ctx, enqueueJobs,
		arg.Kinds,
		arg.ProjectIds,
		arg.Args,
		arg.RunAfters,
	)
	return err
}

const enqueueSymbolicateRelease = `-- name: EnqueueSymbolicateRelease :execrows
INSERT INTO jobs (kind, project_id, args)
SELECT 'symbolicate', e.project_id, jsonb_build_object('event', e.event_id)
FROM events e
WHERE e.project_id = $1 AND e.release = $2 AND e.symbolicated = false AND e.fingerprint IS NOT NULL
  AND e.occurred_at >= $3
ORDER BY e.occurred_at DESC LIMIT $4
`

type EnqueueSymbolicateReleaseParams struct {
	ProjectID  int64     `json:"project_id"`
	Release    *string   `json:"release"`
	OccurredAt time.Time `json:"occurred_at"`
	Limit      int32     `json:"limit"`
}

// Fans a release out into one symbolicate job per unsymbolicated event
// (bounded, newest first) in a single statement: one NOTIFY, and each
// event then retries on its own.
func (q *Queries) EnqueueSymbolicateRelease(ctx context.Context, arg EnqueueSymbolicateReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueSymbolicateRelease,
		arg.ProjectID,
		arg.Release,
		arg.OccurredAt,
		arg.Limit,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireJobs = `-- name: ExpireJobs :execrows
DELETE FROM jobs WHERE attempts >= 8 OR created_at < now() - INTERVAL '7 days'
`

func (q *Queries) ExpireJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseJob = `-- name: ReleaseJob :exec
UPDATE jobs SET locked_until = NULL, attempts = attempts - 1 WHERE id = $1
`

// Shutdown mid-job: give the lease back without counting an attempt.
func (q *Queries) ReleaseJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, releaseJob, id)
	return err
}

const retryJob = `-- name: RetryJob :exec
UPDATE jobs SET last_error = $2, run_after = $3, locked_until = NULL WHERE id = $1
`

type RetryJobParams struct {
	ID        int64     `json:"id"`
	LastError *string   `json:"last_error"`
	RunAfter  time.Time `json:"run_after"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.Exec(ctx, retryJob, arg.ID, arg.LastError, arg.RunAfter)
	return err
}
