// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type AlertChannel struct {
	ID        int64           `json:"id"`
	ProjectID int64           `json:"project_id"`
	Kind      string          `json:"kind"`
	Config    json.RawMessage `json:"config"`
	CreatedAt time.Time       `json:"created_at"`
}

type AlertRule struct {
	ProjectID       int64      `json:"project_id"`
	Type            string     `json:"type"`
	Enabled         bool       `json:"enabled"`
	CooldownMinutes int32      `json:"cooldown_minutes"`
	LastTriggered   *time.Time `json:"last_triggered"`
}

type Event struct {
	OccurredAt    time.Time       `json:"occurred_at"`
	ProjectID     int64           `json:"project_id"`
	EventID       string          `json:"event_id"`
	Level         string          `json:"level"`
	Message       string          `json:"message"`
	Platform      *string         `json:"platform"`
	Environment   *string         `json:"environment"`
	Release       *string         `json:"release"`
	DeviceID      *string         `json:"device_id"`
	DeviceModel   *string         `json:"device_model"`
	OsVersion     *string         `json:"os_version"`
	Screen        *string         `json:"screen"`
	ErrorType     *string         `json:"error_type"`
	ErrorLocation *string         `json:"error_location"`
	Handled       *bool           `json:"handled"`
	SdkName       *string         `json:"sdk_name"`
	UserID        *string         `json:"user_id"`
	Fingerprint   *string         `json:"fingerprint"`
	Symbolicated  bool            `json:"symbolicated"`
	Tags          json.RawMessage `json:"tags"`
	Breadcrumbs   json.RawMessage `json:"breadcrumbs"`
	Payload       json.RawMessage `json:"payload"`
	Symbols       json.RawMessage `json:"symbols"`
}

type EventStatsHourly struct {
	Bucket    time.Time `json:"bucket"`
	ProjectID int64     `json:"project_id"`
	Release   string    `json:"release"`
	Platform  string    `json:"platform"`
	Level     string    `json:"level"`
	Events    int64     `json:"events"`
	Crashes   int64     `json:"crashes"`
	Errors    int64     `json:"errors"`
}

type Issue struct {
	ProjectID       int64     `json:"project_id"`
	Fingerprint     string    `json:"fingerprint"`
	Title           string    `json:"title"`
	Level           string    `json:"level"`
	ErrorType       *string   `json:"error_type"`
	Screen          *string   `json:"screen"`
	Platform        *string   `json:"platform"`
	Status          string    `json:"status"`
	EventCount      int64     `json:"event_count"`
	StoredCount     int64     `json:"stored_count"`
	FirstSeen       time.Time `json:"first_seen"`
	LastSeen        time.Time `json:"last_seen"`
	FirstRelease    *string   `json:"first_release"`
	LastRelease     *string   `json:"last_release"`
	ResolvedRelease *string   `json:"resolved_release"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type IssueStatsHourly struct {
	Bucket      time.Time `json:"bucket"`
	ProjectID   int64     `json:"project_id"`
	Fingerprint string    `json:"fingerprint"`
	Events      int64     `json:"events"`
}

type Job struct {
	ID          int64           `json:"id"`
	Kind        string          `json:"kind"`
	ProjectID   int64           `json:"project_id"`
	Args        json.RawMessage `json:"args"`
	RunAfter    time.Time       `json:"run_after"`
	Attempts    int32           `json:"attempts"`
	LockedUntil *time.Time      `json:"locked_until"`
	LastError   *string         `json:"last_error"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Project struct {
	ID              int64     `json:"id"`
	Slug            string    `json:"slug"`
	Name            string    `json:"name"`
	Platform        *string   `json:"platform"`
	PublicKey       string    `json:"public_key"`
	SampleKeepFirst int32     `json:"sample_keep_first"`
	SampleRate      float64   `json:"sample_rate"`
	DailyQuota      int32     `json:"daily_quota"`
	CreatedAt       time.Time `json:"created_at"`
}

type ProjectUsage struct {
	ProjectID int64     `json:"project_id"`
	Day       time.Time `json:"day"`
	Events    int64     `json:"events"`
}

type ReleaseHealthDaily struct {
	Bucket    time.Time `json:"bucket"`
	ProjectID int64     `json:"project_id"`
	Release   string    `json:"release"`
	Total     int64     `json:"total"`
	Crashed   int64     `json:"crashed"`
	Errored   int64     `json:"errored"`
}

type Session struct {
	StartedAt   time.Time `json:"started_at"`
	ProjectID   int64     `json:"project_id"`
	Sid         string    `json:"sid"`
	Release     string    `json:"release"`
	Environment *string   `json:"environment"`
	Status      string    `json:"status"`
	Count       int32     `json:"count"`
}

type SymbolFile struct {
	ID         int64     `json:"id"`
	ProjectID  int64     `json:"project_id"`
	Kind       string    `json:"kind"`
	Release    string    `json:"release"`
	DebugID    *string   `json:"debug_id"`
	Filename   string    `json:"filename"`
	Size       int64     `json:"size"`
	Data       []byte    `json:"data"`
	UploadedAt time.Time `json:"uploaded_at"`
}

type UploadChunk struct {
	Sha1      string    `json:"sha1"`
	Data      []byte    `json:"data"`
	CreatedAt time.Time `json:"created_at"`
}
