// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/at-least/crashcart/internal/sentry"
)

type AlertType string

const (
	AlertTypeNewIssue         AlertType = "new_issue"
	AlertTypeRegression       AlertType = "regression"
	AlertTypeUnhandledSpike   AlertType = "unhandled_spike"
	AlertTypeEscalating       AlertType = "escalating"
	AlertTypeMonitorFailed    AlertType = "monitor_failed"
	AlertTypeMonitorRecovered AlertType = "monitor_recovered"
)

func (e *AlertType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertType(s)
	case string:
		*e = AlertType(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertType: %T", src)
	}
	return nil
}

type NullAlertType struct {
	AlertType AlertType `json:"alert_type"`
	Valid     bool      `json:"valid"` // Valid is true if AlertType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertType) Scan(value interface{}) error {
	if value == nil {
		ns.AlertType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertType), nil
}

type ChannelKind string

const (
	ChannelKindWebhook  ChannelKind = "webhook"
	ChannelKindSlack    ChannelKind = "slack"
	ChannelKindTelegram ChannelKind = "telegram"
)

func (e *ChannelKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelKind(s)
	case string:
		*e = ChannelKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelKind: %T", src)
	}
	return nil
}

type NullChannelKind struct {
	ChannelKind ChannelKind `json:"channel_kind"`
	Valid       bool        `json:"valid"` // Valid is true if ChannelKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelKind) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelKind), nil
}

type CheckinStatus string

const (
	CheckinStatusInProgress CheckinStatus = "in_progress"
	CheckinStatusOk         CheckinStatus = "ok"
	CheckinStatusError      CheckinStatus = "error"
	CheckinStatusMissed     CheckinStatus = "missed"
	CheckinStatusTimeout    CheckinStatus = "timeout"
)

func (e *CheckinStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckinStatus(s)
	case string:
		*e = CheckinStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckinStatus: %T", src)
	}
	return nil
}

type NullCheckinStatus struct {
	CheckinStatus CheckinStatus `json:"checkin_status"`
	Valid         bool          `json:"valid"` // Valid is true if CheckinStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckinStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CheckinStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckinStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckinStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckinStatus), nil
}

type EventLevel string

const (
	EventLevelFatal   EventLevel = "fatal"
	EventLevelError   EventLevel = "error"
	EventLevelWarning EventLevel = "warning"
	EventLevelInfo    EventLevel = "info"
	EventLevelDebug   EventLevel = "debug"
)

func (e *EventLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventLevel(s)
	case string:
		*e = EventLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for EventLevel: %T", src)
	}
	return nil
}

type NullEventLevel struct {
	EventLevel EventLevel `json:"event_level"`
	Valid      bool       `json:"valid"` // Valid is true if EventLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventLevel) Scan(value interface{}) error {
	if value == nil {
		ns.EventLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventLevel), nil
}

type IssueStatus string

const (
	IssueStatusUnresolved IssueStatus = "unresolved"
	IssueStatusResolved   IssueStatus = "resolved"
	IssueStatusIgnored    IssueStatus = "ignored"
	IssueStatusRegression IssueStatus = "regression"
)

func (e *IssueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueStatus(s)
	case string:
		*e = IssueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueStatus: %T", src)
	}
	return nil
}

type NullIssueStatus struct {
	IssueStatus IssueStatus `json:"issue_status"`
	Valid       bool        `json:"valid"` // Valid is true if IssueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IssueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueStatus), nil
}

type JobKind string

const (
	JobKindSymbolicate   JobKind = "symbolicate"
	JobKindResymbolicate JobKind = "resymbolicate"
	JobKindAlert         JobKind = "alert"
)

func (e *JobKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobKind(s)
	case string:
		*e = JobKind(s)
	default:
		return fmt.Errorf("unsupported scan type for JobKind: %T", src)
	}
	return nil
}

type NullJobKind struct {
	JobKind JobKind `json:"job_kind"`
	Valid   bool    `json:"valid"` // Valid is true if JobKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobKind) Scan(value interface{}) error {
	if value == nil {
		ns.JobKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobKind), nil
}

type SessionStatus string

const (
	SessionStatusOk       SessionStatus = "ok"
	SessionStatusExited   SessionStatus = "exited"
	SessionStatusCrashed  SessionStatus = "crashed"
	SessionStatusErrored  SessionStatus = "errored"
	SessionStatusAbnormal SessionStatus = "abnormal"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type SymbolKind string

const (
	SymbolKindProguard  SymbolKind = "proguard"
	SymbolKindSourcemap SymbolKind = "sourcemap"
	SymbolKindDsym      SymbolKind = "dsym"
)

func (e *SymbolKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SymbolKind(s)
	case string:
		*e = SymbolKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SymbolKind: %T", src)
	}
	return nil
}

type NullSymbolKind struct {
	SymbolKind SymbolKind `json:"symbol_kind"`
	Valid      bool       `json:"valid"` // Valid is true if SymbolKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSymbolKind) Scan(value interface{}) error {
	if value == nil {
		ns.SymbolKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SymbolKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSymbolKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SymbolKind), nil
}

type AlertChannel struct {
	ID        int64           `json:"id"`
	ProjectID int64           `json:"project_id"`
	Kind      ChannelKind     `json:"kind"`
	Config    json.RawMessage `json:"config"`
	CreatedAt time.Time       `json:"created_at"`
}

type AlertRule struct {
	ProjectID       int64      `json:"project_id"`
	Type            AlertType  `json:"type"`
	Enabled         bool       `json:"enabled"`
	CooldownMinutes int32      `json:"cooldown_minutes"`
	LastTriggered   *time.Time `json:"last_triggered"`
}

type ApiKey struct {
	ID         int64      `json:"id"`
	Name       string     `json:"name"`
	KeyHash    []byte     `json:"key_hash"`
	Prefix     string     `json:"prefix"`
	CreatedBy  *int64     `json:"created_by"`
	CreatedAt  time.Time  `json:"created_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

type Attachment struct {
	OccurredAt     time.Time `json:"occurred_at"`
	ProjectID      int64     `json:"project_id"`
	EventID        sentry.ID `json:"event_id"`
	N              int32     `json:"n"`
	Filename       string    `json:"filename"`
	ContentType    string    `json:"content_type"`
	AttachmentType string    `json:"attachment_type"`
	Size           int64     `json:"size"`
	Data           []byte    `json:"data"`
}

type ClientReportCount struct {
	ProjectID int64     `json:"project_id"`
	Bucket    time.Time `json:"bucket"`
	Reason    string    `json:"reason"`
	Category  string    `json:"category"`
	Quantity  int64     `json:"quantity"`
}

type CrashcartSchema struct {
	Version   int32     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
}

type Event struct {
	OccurredAt   time.Time       `json:"occurred_at"`
	ProjectID    int64           `json:"project_id"`
	EventID      sentry.ID       `json:"event_id"`
	Level        EventLevel      `json:"level"`
	Message      string          `json:"message"`
	Platform     *string         `json:"platform"`
	Environment  *string         `json:"environment"`
	Release      *string         `json:"release"`
	DeviceID     *string         `json:"device_id"`
	DeviceModel  *string         `json:"device_model"`
	OsVersion    *string         `json:"os_version"`
	Transaction  *string         `json:"transaction"`
	ErrorType    *string         `json:"error_type"`
	Culprit      *string         `json:"culprit"`
	Handled      *bool           `json:"handled"`
	SdkName      *string         `json:"sdk_name"`
	UserID       *string         `json:"user_id"`
	Fingerprint  *sentry.ID      `json:"fingerprint"`
	Symbolicated bool            `json:"symbolicated"`
	Tags         json.RawMessage `json:"tags"`
	Symbols      json.RawMessage `json:"symbols"`
	Payload      []byte          `json:"payload"`
}

type EventStatsDirty struct {
	ProjectID int64     `json:"project_id"`
	Bucket    time.Time `json:"bucket"`
	Gen       int64     `json:"gen"`
}

type EventStatsHourly struct {
	Bucket    time.Time  `json:"bucket"`
	ProjectID int64      `json:"project_id"`
	Release   string     `json:"release"`
	Platform  string     `json:"platform"`
	Level     EventLevel `json:"level"`
	Events    int64      `json:"events"`
	Unhandled int64      `json:"unhandled"`
	Errors    int64      `json:"errors"`
}

type EventStatsHourlyRolled struct {
	Bucket    time.Time  `json:"bucket"`
	ProjectID int64      `json:"project_id"`
	Release   string     `json:"release"`
	Platform  string     `json:"platform"`
	Level     EventLevel `json:"level"`
	Events    int64      `json:"events"`
	Unhandled int64      `json:"unhandled"`
	Errors    int64      `json:"errors"`
}

type Issue struct {
	ProjectID             int64       `json:"project_id"`
	Fingerprint           sentry.ID   `json:"fingerprint"`
	Title                 string      `json:"title"`
	Level                 EventLevel  `json:"level"`
	ErrorType             *string     `json:"error_type"`
	Transaction           *string     `json:"transaction"`
	Platform              *string     `json:"platform"`
	Status                IssueStatus `json:"status"`
	StatusBy              *string     `json:"status_by"`
	EventCount            int64       `json:"event_count"`
	StoredCount           int64       `json:"stored_count"`
	FirstSeen             time.Time   `json:"first_seen"`
	LastSeen              time.Time   `json:"last_seen"`
	FirstRelease          *string     `json:"first_release"`
	LastRelease           *string     `json:"last_release"`
	Releases              []string    `json:"releases"`
	ResolvedReleases      []string    `json:"resolved_releases"`
	IgnoreUntil           *time.Time  `json:"ignore_until"`
	IgnoreUntilCount      *int64      `json:"ignore_until_count"`
	IgnoreUntilEscalating bool        `json:"ignore_until_escalating"`
	IgnoreBaseline        *int64      `json:"ignore_baseline"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

type IssueStatsHourly struct {
	Bucket      time.Time `json:"bucket"`
	ProjectID   int64     `json:"project_id"`
	Fingerprint sentry.ID `json:"fingerprint"`
	Events      int64     `json:"events"`
}

type IssueStatsHourlyRolled struct {
	Bucket      time.Time `json:"bucket"`
	ProjectID   int64     `json:"project_id"`
	Fingerprint sentry.ID `json:"fingerprint"`
	Events      int64     `json:"events"`
}

type Job struct {
	ID          int64           `json:"id"`
	Kind        JobKind         `json:"kind"`
	ProjectID   int64           `json:"project_id"`
	Args        json.RawMessage `json:"args"`
	RunAfter    time.Time       `json:"run_after"`
	Attempts    int32           `json:"attempts"`
	LockedUntil *time.Time      `json:"locked_until"`
	LastError   *string         `json:"last_error"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Monitor struct {
	ProjectID            int64             `json:"project_id"`
	Slug                 string            `json:"slug"`
	ScheduleType         string            `json:"schedule_type"`
	ScheduleValue        string            `json:"schedule_value"`
	ScheduleUnit         *string           `json:"schedule_unit"`
	Timezone             string            `json:"timezone"`
	CheckinMarginMin     int32             `json:"checkin_margin_min"`
	MaxRuntimeMin        int32             `json:"max_runtime_min"`
	FailureThreshold     int32             `json:"failure_threshold"`
	RecoveryThreshold    int32             `json:"recovery_threshold"`
	LastStatus           NullCheckinStatus `json:"last_status"`
	ConsecutiveFailures  int32             `json:"consecutive_failures"`
	ConsecutiveSuccesses int32             `json:"consecutive_successes"`
	Alerting             bool              `json:"alerting"`
	NextExpectedAt       *time.Time        `json:"next_expected_at"`
	LastCheckinAt        *time.Time        `json:"last_checkin_at"`
	CreatedAt            time.Time         `json:"created_at"`
}

type MonitorCheckin struct {
	StartedAt   time.Time     `json:"started_at"`
	ProjectID   int64         `json:"project_id"`
	MonitorSlug string        `json:"monitor_slug"`
	CheckInID   sentry.ID     `json:"check_in_id"`
	Status      CheckinStatus `json:"status"`
	DurationS   *float32      `json:"duration_s"`
	Release     *string       `json:"release"`
	Environment *string       `json:"environment"`
}

type Project struct {
	ID              int64     `json:"id"`
	Slug            string    `json:"slug"`
	Name            string    `json:"name"`
	Platform        *string   `json:"platform"`
	PublicKey       string    `json:"public_key"`
	SampleKeepFirst int32     `json:"sample_keep_first"`
	SampleRate      float64   `json:"sample_rate"`
	DailyQuota      int32     `json:"daily_quota"`
	CreatedAt       time.Time `json:"created_at"`
}

type ProjectUsage struct {
	ProjectID int64     `json:"project_id"`
	Day       time.Time `json:"day"`
	Events    int64     `json:"events"`
}

type Release struct {
	ProjectID int64     `json:"project_id"`
	Release   string    `json:"release"`
	Platforms []string  `json:"platforms"`
	FirstSeen time.Time `json:"first_seen"`
}

type ReleaseHealthHourly struct {
	Bucket    time.Time `json:"bucket"`
	ProjectID int64     `json:"project_id"`
	Release   string    `json:"release"`
	Total     int64     `json:"total"`
	Crashed   int64     `json:"crashed"`
	Errored   int64     `json:"errored"`
}

type ReleaseHealthHourlyRolled struct {
	Bucket    time.Time `json:"bucket"`
	ProjectID int64     `json:"project_id"`
	Release   string    `json:"release"`
	Total     int64     `json:"total"`
	Crashed   int64     `json:"crashed"`
	Errored   int64     `json:"errored"`
}

type Session struct {
	StartedAt   time.Time     `json:"started_at"`
	ProjectID   int64         `json:"project_id"`
	Sid         string        `json:"sid"`
	Release     string        `json:"release"`
	Environment *string       `json:"environment"`
	Status      SessionStatus `json:"status"`
	Count       int32         `json:"count"`
}

type SessionStatsDirty struct {
	ProjectID int64     `json:"project_id"`
	Bucket    time.Time `json:"bucket"`
	Gen       int64     `json:"gen"`
}

type SymbolFile struct {
	ID         int64      `json:"id"`
	ProjectID  int64      `json:"project_id"`
	Kind       SymbolKind `json:"kind"`
	Release    *string    `json:"release"`
	DebugID    *string    `json:"debug_id"`
	Filename   string     `json:"filename"`
	Size       int64      `json:"size"`
	Data       []byte     `json:"data"`
	UploadedAt time.Time  `json:"uploaded_at"`
}

type UploadChunk struct {
	Sha1      string    `json:"sha1"`
	Data      []byte    `json:"data"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserReport struct {
	ProjectID  int64     `json:"project_id"`
	EventID    sentry.ID `json:"event_id"`
	ReceivedAt time.Time `json:"received_at"`
	Name       *string   `json:"name"`
	Email      *string   `json:"email"`
	Comments   string    `json:"comments"`
}

type UserSession struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}
