// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package sqlc

import (
	"context"
	"time"

	"github.com/at-least/crashcart/internal/sentry"
)

const deleteMonitor = `-- name: DeleteMonitor :execrows
DELETE FROM monitors WHERE project_id = $1 AND slug = $2
`

type DeleteMonitorParams struct {
	ProjectID int64  `json:"project_id"`
	Slug      string `json:"slug"`
}

func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMonitor, arg.ProjectID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dueMonitors = `-- name: DueMonitors :many
SELECT project_id, slug, schedule_type, schedule_value, schedule_unit, timezone, checkin_margin_min, max_runtime_min, failure_threshold, recovery_threshold, last_status, consecutive_failures, consecutive_successes, alerting, next_expected_at, last_checkin_at, created_at FROM monitors WHERE next_expected_at IS NOT NULL AND next_expected_at < $1::timestamptz
`

// Monitors whose next expected check-in has passed (alerts.CheckMonitors,
// every minute): each becomes one synthetic `missed` check-in.
func (q *Queries) DueMonitors(ctx context.Context, now time.Time) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, dueMonitors, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ProjectID,
			&i.Slug,
			&i.ScheduleType,
			&i.ScheduleValue,
			&i.ScheduleUnit,
			&i.Timezone,
			&i.CheckinMarginMin,
			&i.MaxRuntimeMin,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.LastStatus,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.Alerting,
			&i.NextExpectedAt,
			&i.LastCheckinAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOpenCheckIn = `-- name: FindOpenCheckIn :one
SELECT started_at, project_id, monitor_slug, check_in_id, status, duration_s, release, environment FROM monitor_checkins
WHERE project_id = $1 AND monitor_slug = $2
  AND (($3::bool AND status = 'in_progress') OR (NOT $3::bool AND check_in_id = $4::uuid))
ORDER BY started_at DESC LIMIT 1
`

type FindOpenCheckInParams struct {
	ProjectID   int64     `json:"project_id"`
	MonitorSlug string    `json:"monitor_slug"`
	Zero        bool      `json:"zero"`
	CheckInID   sentry.ID `json:"check_in_id"`
}

// The row a check-in item resolves to before writing: by its own
// check_in_id, or — the all-zero shorthand — the monitor's latest
// in_progress row. No match means a fresh row (a new check_in_id, or a
// zero id with nothing open to update).
func (q *Queries) FindOpenCheckIn(ctx context.Context, arg FindOpenCheckInParams) (MonitorCheckin, error) {
	row := q.db.QueryRow(ctx, findOpenCheckIn,
		arg.ProjectID,
		arg.MonitorSlug,
		arg.Zero,
		arg.CheckInID,
	)
	var i MonitorCheckin
	err := row.Scan(
		&i.StartedAt,
		&i.ProjectID,
		&i.MonitorSlug,
		&i.CheckInID,
		&i.Status,
		&i.DurationS,
		&i.Release,
		&i.Environment,
	)
	return i, err
}

const getMonitor = `-- name: GetMonitor :one
SELECT project_id, slug, schedule_type, schedule_value, schedule_unit, timezone, checkin_margin_min, max_runtime_min, failure_threshold, recovery_threshold, last_status, consecutive_failures, consecutive_successes, alerting, next_expected_at, last_checkin_at, created_at FROM monitors WHERE project_id = $1 AND slug = $2
`

type GetMonitorParams struct {
	ProjectID int64  `json:"project_id"`
	Slug      string `json:"slug"`
}

func (q *Queries) GetMonitor(ctx context.Context, arg GetMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitor, arg.ProjectID, arg.Slug)
	var i Monitor
	err := row.Scan(
		&i.ProjectID,
		&i.Slug,
		&i.ScheduleType,
		&i.ScheduleValue,
		&i.ScheduleUnit,
		&i.Timezone,
		&i.CheckinMarginMin,
		&i.MaxRuntimeMin,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.LastStatus,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.Alerting,
		&i.NextExpectedAt,
		&i.LastCheckinAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertCheckIn = `-- name: InsertCheckIn :exec
INSERT INTO monitor_checkins (started_at, project_id, monitor_slug, check_in_id, status, duration_s, release, environment)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertCheckInParams struct {
	StartedAt   time.Time     `json:"started_at"`
	ProjectID   int64         `json:"project_id"`
	MonitorSlug string        `json:"monitor_slug"`
	CheckInID   sentry.ID     `json:"check_in_id"`
	Status      CheckinStatus `json:"status"`
	DurationS   *float32      `json:"duration_s"`
	Release     *string       `json:"release"`
	Environment *string       `json:"environment"`
}

func (q *Queries) InsertCheckIn(ctx context.Context, arg InsertCheckInParams) error {
	_, err := q.db.Exec(ctx, insertCheckIn,
		arg.StartedAt,
		arg.ProjectID,
		arg.MonitorSlug,
		arg.CheckInID,
		arg.Status,
		arg.DurationS,
		arg.Release,
		arg.Environment,
	)
	return err
}

const listCheckIns = `-- name: ListCheckIns :many
SELECT started_at, project_id, monitor_slug, check_in_id, status, duration_s, release, environment FROM monitor_checkins WHERE project_id = $1 AND monitor_slug = $2 ORDER BY started_at DESC, check_in_id DESC LIMIT $3
`

type ListCheckInsParams struct {
	ProjectID   int64  `json:"project_id"`
	MonitorSlug string `json:"monitor_slug"`
	Limit       int32  `json:"limit"`
}

// One monitor's recent check-ins, newest first: the Monitors detail page.
func (q *Queries) ListCheckIns(ctx context.Context, arg ListCheckInsParams) ([]MonitorCheckin, error) {
	rows, err := q.db.Query(ctx, listCheckIns, arg.ProjectID, arg.MonitorSlug, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorCheckin{}
	for rows.Next() {
		var i MonitorCheckin
		if err := rows.Scan(
			&i.StartedAt,
			&i.ProjectID,
			&i.MonitorSlug,
			&i.CheckInID,
			&i.Status,
			&i.DurationS,
			&i.Release,
			&i.Environment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
SELECT project_id, slug, schedule_type, schedule_value, schedule_unit, timezone, checkin_margin_min, max_runtime_min, failure_threshold, recovery_threshold, last_status, consecutive_failures, consecutive_successes, alerting, next_expected_at, last_checkin_at, created_at FROM monitors WHERE project_id = $1 ORDER BY slug
`

// Project-scoped, alphabetical: the Monitors page and its API.
func (q *Queries) ListMonitors(ctx context.Context, projectID int64) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ProjectID,
			&i.Slug,
			&i.ScheduleType,
			&i.ScheduleValue,
			&i.ScheduleUnit,
			&i.Timezone,
			&i.CheckinMarginMin,
			&i.MaxRuntimeMin,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.LastStatus,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.Alerting,
			&i.NextExpectedAt,
			&i.LastCheckinAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMonitorResult = `-- name: RecordMonitorResult :exec
UPDATE monitors SET
    last_status = $3::checkin_status,
    consecutive_failures = $4::int,
    consecutive_successes = $5::int,
    alerting = $6::bool,
    next_expected_at = $7::timestamptz,
    last_checkin_at = $8::timestamptz
WHERE project_id = $1 AND slug = $2
`

type RecordMonitorResultParams struct {
	ProjectID            int64         `json:"project_id"`
	Slug                 string        `json:"slug"`
	LastStatus           CheckinStatus `json:"last_status"`
	ConsecutiveFailures  int32         `json:"consecutive_failures"`
	ConsecutiveSuccesses int32         `json:"consecutive_successes"`
	Alerting             bool          `json:"alerting"`
	NextExpectedAt       time.Time     `json:"next_expected_at"`
	LastCheckinAt        time.Time     `json:"last_checkin_at"`
}

// Advances a monitor's state after a terminal check-in (ingest) or a
// missed/timeout detection (alerts.CheckMonitors) — never after an
// in_progress one. next_expected_at and the consecutive counters are
// computed in Go (the schedule math needs the parsed cron/interval
// schedule); this just writes the result.
func (q *Queries) RecordMonitorResult(ctx context.Context, arg RecordMonitorResultParams) error {
	_, err := q.db.Exec(ctx, recordMonitorResult,
		arg.ProjectID,
		arg.Slug,
		arg.LastStatus,
		arg.ConsecutiveFailures,
		arg.ConsecutiveSuccesses,
		arg.Alerting,
		arg.NextExpectedAt,
		arg.LastCheckinAt,
	)
	return err
}

const timedOutCheckIns = `-- name: TimedOutCheckIns :many
SELECT c.project_id, c.monitor_slug, c.check_in_id, c.started_at
FROM monitor_checkins c JOIN monitors m ON m.project_id = c.project_id AND m.slug = c.monitor_slug
WHERE c.status = 'in_progress' AND c.started_at + make_interval(mins => m.max_runtime_min) < $1
`

type TimedOutCheckInsRow struct {
	ProjectID   int64     `json:"project_id"`
	MonitorSlug string    `json:"monitor_slug"`
	CheckInID   sentry.ID `json:"check_in_id"`
	StartedAt   time.Time `json:"started_at"`
}

// in_progress check-ins that outlived their monitor's max_runtime_min
// (alerts.CheckMonitors): each is flipped to `timeout`.
func (q *Queries) TimedOutCheckIns(ctx context.Context, startedAt time.Time) ([]TimedOutCheckInsRow, error) {
	rows, err := q.db.Query(ctx, timedOutCheckIns, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimedOutCheckInsRow{}
	for rows.Next() {
		var i TimedOutCheckInsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.MonitorSlug,
			&i.CheckInID,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckIn = `-- name: UpdateCheckIn :exec
UPDATE monitor_checkins SET status = $5, duration_s = COALESCE($6::real, duration_s),
    release = COALESCE($7::text, release), environment = COALESCE($8::text, environment)
WHERE project_id = $1 AND monitor_slug = $2 AND check_in_id = $3 AND started_at = $4
`

type UpdateCheckInParams struct {
	ProjectID   int64         `json:"project_id"`
	MonitorSlug string        `json:"monitor_slug"`
	CheckInID   sentry.ID     `json:"check_in_id"`
	StartedAt   time.Time     `json:"started_at"`
	Status      CheckinStatus `json:"status"`
	DurationS   *float32      `json:"duration_s"`
	Release     *string       `json:"release"`
	Environment *string       `json:"environment"`
}

// A later check-in of the same run (the same check_in_id, or the
// all-zero shorthand resolved by FindOpenCheckIn to an existing row):
// status advances, duration/release/environment are kept if this one
// did not send them. started_at (the partition key) is never touched.
func (q *Queries) UpdateCheckIn(ctx context.Context, arg UpdateCheckInParams) error {
	_, err := q.db.Exec(ctx, updateCheckIn,
		arg.ProjectID,
		arg.MonitorSlug,
		arg.CheckInID,
		arg.StartedAt,
		arg.Status,
		arg.DurationS,
		arg.Release,
		arg.Environment,
	)
	return err
}

const upsertMonitor = `-- name: UpsertMonitor :one
INSERT INTO monitors (project_id, slug, schedule_type, schedule_value, schedule_unit, timezone,
                      checkin_margin_min, max_runtime_min, failure_threshold, recovery_threshold)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (project_id, slug) DO UPDATE SET
    schedule_type = EXCLUDED.schedule_type, schedule_value = EXCLUDED.schedule_value, schedule_unit = EXCLUDED.schedule_unit,
    timezone = EXCLUDED.timezone, checkin_margin_min = EXCLUDED.checkin_margin_min, max_runtime_min = EXCLUDED.max_runtime_min,
    failure_threshold = EXCLUDED.failure_threshold, recovery_threshold = EXCLUDED.recovery_threshold
RETURNING project_id, slug, schedule_type, schedule_value, schedule_unit, timezone, checkin_margin_min, max_runtime_min, failure_threshold, recovery_threshold, last_status, consecutive_failures, consecutive_successes, alerting, next_expected_at, last_checkin_at, created_at
`

type UpsertMonitorParams struct {
	ProjectID         int64   `json:"project_id"`
	Slug              string  `json:"slug"`
	ScheduleType      string  `json:"schedule_type"`
	ScheduleValue     string  `json:"schedule_value"`
	ScheduleUnit      *string `json:"schedule_unit"`
	Timezone          string  `json:"timezone"`
	CheckinMarginMin  int32   `json:"checkin_margin_min"`
	MaxRuntimeMin     int32   `json:"max_runtime_min"`
	FailureThreshold  int32   `json:"failure_threshold"`
	RecoveryThreshold int32   `json:"recovery_threshold"`
}

// The SDK's monitor_config upsert: schedule/thresholds are overwritten,
// state (last_status, consecutive_*, next_expected_at, last_checkin_at)
// is untouched — a re-upload of the same schedule must not reset a
// monitor's alerting history.
func (q *Queries) UpsertMonitor(ctx context.Context, arg UpsertMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, upsertMonitor,
		arg.ProjectID,
		arg.Slug,
		arg.ScheduleType,
		arg.ScheduleValue,
		arg.ScheduleUnit,
		arg.Timezone,
		arg.CheckinMarginMin,
		arg.MaxRuntimeMin,
		arg.FailureThreshold,
		arg.RecoveryThreshold,
	)
	var i Monitor
	err := row.Scan(
		&i.ProjectID,
		&i.Slug,
		&i.ScheduleType,
		&i.ScheduleValue,
		&i.ScheduleUnit,
		&i.Timezone,
		&i.CheckinMarginMin,
		&i.MaxRuntimeMin,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.LastStatus,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.Alerting,
		&i.NextExpectedAt,
		&i.LastCheckinAt,
		&i.CreatedAt,
	)
	return i, err
}
