// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package sqlc

import (
	"context"
	"time"
)

const listReleases = `-- name: ListReleases :many
SELECT project_id, release, platforms, first_seen FROM releases WHERE project_id = $1 ORDER BY first_seen DESC, release DESC LIMIT $2
`

type ListReleasesParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int32 `json:"limit"`
}

// Newest first (by first appearance).
func (q *Queries) ListReleases(ctx context.Context, arg ListReleasesParams) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleases, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ProjectID,
			&i.Release,
			&i.Platforms,
			&i.FirstSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReleases = `-- name: UpsertReleases :exec
INSERT INTO releases (project_id, release, platforms, first_seen)
SELECT $1::bigint, u.r, CASE WHEN u.p = '' THEN '{}'::text[] ELSE ARRAY[u.p] END, u.t
FROM (SELECT unnest($2::text[]) AS r, unnest($3::text[]) AS p,
             unnest($4::timestamptz[]) AS t) AS u
ON CONFLICT (project_id, release) DO UPDATE SET
    platforms  = (SELECT array_agg(DISTINCT x ORDER BY x) FROM unnest(releases.platforms || EXCLUDED.platforms) AS x),
    first_seen = LEAST(releases.first_seen, EXCLUDED.first_seen)
WHERE NOT releases.platforms @> EXCLUDED.platforms OR EXCLUDED.first_seen < releases.first_seen
`

type UpsertReleasesParams struct {
	ProjectID  int64       `json:"project_id"`
	Releases   []string    `json:"releases"`
	Platforms  []string    `json:"platforms"`
	FirstSeens []time.Time `json:"first_seens"`
}

// Records the releases an envelope mentions. The conflict update only
// fires when it would change something (a new platform, an earlier
// first_seen), so the usual envelope leaves the row untouched.
func (q *Queries) UpsertReleases(ctx context.Context, arg UpsertReleasesParams) error {
	_, err := q.db.Exec(ctx, upsertReleases,
		arg.ProjectID,
		arg.Releases,
		arg.Platforms,
		arg.FirstSeens,
	)
	return err
}
