// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
)

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, project_id, release, environment, status, count)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    status = CASE WHEN sessions.status = 'ok' OR EXCLUDED.status <> 'ok' THEN EXCLUDED.status ELSE sessions.status END
`

type InsertSessionParams struct {
	ID          int64   `json:"id"`
	ProjectID   int64   `json:"project_id"`
	Release     string  `json:"release"`
	Environment *string `json:"environment"`
	Status      string  `json:"status"`
	Count       int32   `json:"count"`
}

// Updates of one session (same sid → same id, see ingest) overwrite the
// status, except that a terminal status is never downgraded to 'ok'.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.ProjectID,
		arg.Release,
		arg.Environment,
		arg.Status,
		arg.Count,
	)
	return err
}

const releaseHealth = `-- name: ReleaseHealth :many
SELECT release,
       COALESCE(sum(total), 0)::bigint   AS total,
       COALESCE(sum(crashed), 0)::bigint AS crashed,
       COALESCE(sum(errored), 0)::bigint AS errored
FROM release_health_daily
WHERE project_id = $1 AND bucket >= $2 AND bucket < $3
GROUP BY release
`

type ReleaseHealthParams struct {
	ProjectID int64 `json:"project_id"`
	Bucket    int64 `json:"bucket"`
	Bucket_2  int64 `json:"bucket_2"`
}

type ReleaseHealthRow struct {
	Release string `json:"release"`
	Total   int64  `json:"total"`
	Crashed int64  `json:"crashed"`
	Errored int64  `json:"errored"`
}

// Per release over a window: sessions and crash-free rate inputs.
func (q *Queries) ReleaseHealth(ctx context.Context, arg ReleaseHealthParams) ([]ReleaseHealthRow, error) {
	rows, err := q.db.Query(ctx, releaseHealth, arg.ProjectID, arg.Bucket, arg.Bucket_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseHealthRow{}
	for rows.Next() {
		var i ReleaseHealthRow
		if err := rows.Scan(
			&i.Release,
			&i.Total,
			&i.Crashed,
			&i.Errored,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseHealthDaily = `-- name: ReleaseHealthDaily :many
SELECT bucket, COALESCE(sum(total), 0)::bigint AS total, COALESCE(sum(crashed), 0)::bigint AS crashed, COALESCE(sum(errored), 0)::bigint AS errored
FROM release_health_daily
WHERE project_id = $1 AND release = $2 AND bucket >= $3 AND bucket < $4
GROUP BY bucket ORDER BY bucket
`

type ReleaseHealthDailyParams struct {
	ProjectID int64  `json:"project_id"`
	Release   string `json:"release"`
	Bucket    int64  `json:"bucket"`
	Bucket_2  int64  `json:"bucket_2"`
}

type ReleaseHealthDailyRow struct {
	Bucket  int64 `json:"bucket"`
	Total   int64 `json:"total"`
	Crashed int64 `json:"crashed"`
	Errored int64 `json:"errored"`
}

func (q *Queries) ReleaseHealthDaily(ctx context.Context, arg ReleaseHealthDailyParams) ([]ReleaseHealthDailyRow, error) {
	rows, err := q.db.Query(ctx, releaseHealthDaily,
		arg.ProjectID,
		arg.Release,
		arg.Bucket,
		arg.Bucket_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseHealthDailyRow{}
	for rows.Next() {
		var i ReleaseHealthDailyRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Total,
			&i.Crashed,
			&i.Errored,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
