// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spool.sql

package sqlc

import (
	"context"
	"time"
)

const advancePack = `-- name: AdvancePack :one
UPDATE packs SET next_offset = next_offset + $2::bigint, closed = next_offset + $2::bigint >= $3::bigint
WHERE pack_key = $1 RETURNING (next_offset - $2::bigint)::bigint AS off, closed
`

type AdvancePackParams struct {
	PackKey  string `json:"pack_key"`
	N        int64  `json:"n"`
	MaxBytes int64  `json:"max_bytes"`
}

type AdvancePackRow struct {
	Off    int64 `json:"off"`
	Closed bool  `json:"closed"`
}

// Reserves n bytes in a claimed pack; the pack closes when that reaches
// max_bytes. Rolling the transaction back returns the bytes: no gaps.
func (q *Queries) AdvancePack(ctx context.Context, arg AdvancePackParams) (AdvancePackRow, error) {
	row := q.db.QueryRow(ctx, advancePack, arg.PackKey, arg.N, arg.MaxBytes)
	var i AdvancePackRow
	err := row.Scan(&i.Off, &i.Closed)
	return i, err
}

const claimOpenPack = `-- name: ClaimOpenPack :one

SELECT pack_key, next_offset FROM packs WHERE NOT closed
ORDER BY next_offset DESC LIMIT 1 FOR UPDATE SKIP LOCKED
`

type ClaimOpenPackRow struct {
	PackKey    string `json:"pack_key"`
	NextOffset int64  `json:"next_offset"`
}

// Payload packs: packs is the set of pack objects being filled (closed =
// false, any number, chosen with SKIP LOCKED so concurrent envelopes never
// wait on each other) or waiting for upload (closed = true);
// payload_spool holds the payloads of those packs, each at its offset.
// The event row's payload_ref was written with them.
// The fullest open pack no other transaction is writing to (its row lock
// is ours until commit). ErrNoRows: open one (OpenPack).
func (q *Queries) ClaimOpenPack(ctx context.Context) (ClaimOpenPackRow, error) {
	row := q.db.QueryRow(ctx, claimOpenPack)
	var i ClaimOpenPackRow
	err := row.Scan(&i.PackKey, &i.NextOffset)
	return i, err
}

const closeOpenPacks = `-- name: CloseOpenPacks :execrows
UPDATE packs SET closed = true WHERE NOT closed
`

// Everything waiting goes out now (the CLI after an import or seed).
func (q *Queries) CloseOpenPacks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, closeOpenPacks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closedPacks = `-- name: ClosedPacks :many
SELECT pack_key FROM packs WHERE closed ORDER BY created_at
`

func (q *Queries) ClosedPacks(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, closedPacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var pack_key string
		if err := rows.Scan(&pack_key); err != nil {
			return nil, err
		}
		items = append(items, pack_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSpool = `-- name: CountSpool :one
SELECT count(*) FROM payload_spool
`

func (q *Queries) CountSpool(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSpool)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePack = `-- name: DeletePack :exec
DELETE FROM payload_spool WHERE pack_key = $1
`

func (q *Queries) DeletePack(ctx context.Context, packKey string) error {
	_, err := q.db.Exec(ctx, deletePack, packKey)
	return err
}

const deletePackRow = `-- name: DeletePackRow :exec
DELETE FROM packs WHERE pack_key = $1
`

func (q *Queries) DeletePackRow(ctx context.Context, packKey string) error {
	_, err := q.db.Exec(ctx, deletePackRow, packKey)
	return err
}

const expireSpool = `-- name: ExpireSpool :execrows
DELETE FROM payload_spool WHERE created_at < $1
`

// Rows older than retention: their events are gone (a pack that never
// filled on a very quiet project).
func (q *Queries) ExpireSpool(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expireSpool, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockClosedPack = `-- name: LockClosedPack :one
SELECT pack_key FROM packs WHERE pack_key = $1 AND closed FOR UPDATE SKIP LOCKED
`

// Claims a closed pack for upload; another process's claim is skipped.
func (q *Queries) LockClosedPack(ctx context.Context, packKey string) (string, error) {
	row := q.db.QueryRow(ctx, lockClosedPack, packKey)
	var pack_key string
	err := row.Scan(&pack_key)
	return pack_key, err
}

const openPack = `-- name: OpenPack :one
INSERT INTO packs (pack_key) VALUES ($1) RETURNING pack_key, next_offset
`

type OpenPackRow struct {
	PackKey    string `json:"pack_key"`
	NextOffset int64  `json:"next_offset"`
}

func (q *Queries) OpenPack(ctx context.Context, packKey string) (OpenPackRow, error) {
	row := q.db.QueryRow(ctx, openPack, packKey)
	var i OpenPackRow
	err := row.Scan(&i.PackKey, &i.NextOffset)
	return i, err
}

const packRows = `-- name: PackRows :many
SELECT "offset", data FROM payload_spool WHERE pack_key = $1 ORDER BY "offset"
`

type PackRowsRow struct {
	Offset int64  `json:"offset"`
	Data   []byte `json:"data"`
}

func (q *Queries) PackRows(ctx context.Context, packKey string) ([]PackRowsRow, error) {
	rows, err := q.db.Query(ctx, packRows, packKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackRowsRow{}
	for rows.Next() {
		var i PackRowsRow
		if err := rows.Scan(&i.Offset, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spoolPayloads = `-- name: SpoolPayloads :exec
INSERT INTO payload_spool (pack_key, "offset", data, size)
SELECT d.pack_key, d.off, d.data, octet_length(d.data)
FROM (SELECT unnest($1::text[]) AS pack_key, unnest($2::bigint[]) AS off, unnest($3::bytea[]) AS data) AS d
ON CONFLICT (pack_key, "offset") DO NOTHING
`

type SpoolPayloadsParams struct {
	PackKeys []string `json:"pack_keys"`
	Offsets  []int64  `json:"offsets"`
	Datas    [][]byte `json:"datas"`
}

func (q *Queries) SpoolPayloads(ctx context.Context, arg SpoolPayloadsParams) error {
	_, err := q.db.Exec(ctx, spoolPayloads, arg.PackKeys, arg.Offsets, arg.Datas)
	return err
}

const spooledPayload = `-- name: SpooledPayload :one
SELECT data FROM payload_spool WHERE pack_key = $1 AND "offset" = $2
`

type SpooledPayloadParams struct {
	PackKey string `json:"pack_key"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) SpooledPayload(ctx context.Context, arg SpooledPayloadParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, spooledPayload, arg.PackKey, arg.Offset)
	var data []byte
	err := row.Scan(&data)
	return data, err
}
