// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spool.sql

package sqlc

import (
	"context"
	"time"
)

const advancePack = `-- name: AdvancePack :one
UPDATE packs SET next_offset = next_offset + $2::bigint, closed = next_offset + $2::bigint >= $3::bigint
WHERE id = $1 RETURNING (next_offset - $2::bigint)::bigint AS off, closed
`

type AdvancePackParams struct {
	ID       int64 `json:"id"`
	N        int64 `json:"n"`
	MaxBytes int64 `json:"max_bytes"`
}

type AdvancePackRow struct {
	Off    int64 `json:"off"`
	Closed bool  `json:"closed"`
}

// Reserves n bytes in a claimed pack; the pack closes when that reaches
// max_bytes. Rolling the transaction back returns the bytes: no gaps.
func (q *Queries) AdvancePack(ctx context.Context, arg AdvancePackParams) (AdvancePackRow, error) {
	row := q.db.QueryRow(ctx, advancePack, arg.ID, arg.N, arg.MaxBytes)
	var i AdvancePackRow
	err := row.Scan(&i.Off, &i.Closed)
	return i, err
}

const claimOpenPack = `-- name: ClaimOpenPack :one

SELECT id, next_offset FROM packs WHERE NOT closed
ORDER BY next_offset DESC LIMIT 1 FOR UPDATE SKIP LOCKED
`

type ClaimOpenPackRow struct {
	ID         int64 `json:"id"`
	NextOffset int64 `json:"next_offset"`
}

// Payload packs: packs is the set of pack objects being filled (closed =
// false, any number, chosen with SKIP LOCKED so concurrent envelopes never
// wait on each other) or waiting for upload (closed = true);
// payload_spool holds the payloads of those packs, each at its offset.
// The event row's pack_id / pack_offset / pack_len were written with them.
// The fullest open pack no other transaction is writing to (its row lock
// is ours until commit). ErrNoRows: open one (OpenPack).
func (q *Queries) ClaimOpenPack(ctx context.Context) (ClaimOpenPackRow, error) {
	row := q.db.QueryRow(ctx, claimOpenPack)
	var i ClaimOpenPackRow
	err := row.Scan(&i.ID, &i.NextOffset)
	return i, err
}

const closeOpenPacks = `-- name: CloseOpenPacks :execrows
UPDATE packs SET closed = true WHERE NOT closed
`

// Everything waiting goes out now (the CLI after an import or seed).
func (q *Queries) CloseOpenPacks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, closeOpenPacks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closedPacks = `-- name: ClosedPacks :many
SELECT id FROM packs WHERE closed ORDER BY id
`

func (q *Queries) ClosedPacks(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, closedPacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSpool = `-- name: CountSpool :one
SELECT count(*) FROM payload_spool
`

func (q *Queries) CountSpool(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSpool)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePack = `-- name: DeletePack :exec
DELETE FROM packs WHERE id = $1
`

// The spool rows go with it (ON DELETE CASCADE).
func (q *Queries) DeletePack(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePack, id)
	return err
}

const expireSpool = `-- name: ExpireSpool :execrows
DELETE FROM payload_spool WHERE created_at < $1
`

// Rows older than retention: their events are gone (a pack that never
// filled on a very quiet project).
func (q *Queries) ExpireSpool(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expireSpool, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockClosedPack = `-- name: LockClosedPack :one
SELECT id FROM packs WHERE id = $1 AND closed FOR UPDATE SKIP LOCKED
`

// Claims a closed pack for upload; another process's claim is skipped.
func (q *Queries) LockClosedPack(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockClosedPack, id)
	err := row.Scan(&id)
	return id, err
}

const openPack = `-- name: OpenPack :one
INSERT INTO packs DEFAULT VALUES RETURNING id, next_offset
`

type OpenPackRow struct {
	ID         int64 `json:"id"`
	NextOffset int64 `json:"next_offset"`
}

func (q *Queries) OpenPack(ctx context.Context) (OpenPackRow, error) {
	row := q.db.QueryRow(ctx, openPack)
	var i OpenPackRow
	err := row.Scan(&i.ID, &i.NextOffset)
	return i, err
}

const packRows = `-- name: PackRows :many
SELECT "offset", data FROM payload_spool WHERE pack_id = $1 ORDER BY "offset"
`

type PackRowsRow struct {
	Offset int32  `json:"offset"`
	Data   []byte `json:"data"`
}

func (q *Queries) PackRows(ctx context.Context, packID int64) ([]PackRowsRow, error) {
	rows, err := q.db.Query(ctx, packRows, packID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackRowsRow{}
	for rows.Next() {
		var i PackRowsRow
		if err := rows.Scan(&i.Offset, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spoolPayloads = `-- name: SpoolPayloads :exec
INSERT INTO payload_spool (pack_id, "offset", data, size)
SELECT d.pack_id, d.off, d.data, octet_length(d.data)
FROM (SELECT unnest($1::bigint[]) AS pack_id, unnest($2::int[]) AS off, unnest($3::bytea[]) AS data) AS d
ON CONFLICT (pack_id, "offset") DO NOTHING
`

type SpoolPayloadsParams struct {
	PackIds []int64  `json:"pack_ids"`
	Offsets []int32  `json:"offsets"`
	Datas   [][]byte `json:"datas"`
}

func (q *Queries) SpoolPayloads(ctx context.Context, arg SpoolPayloadsParams) error {
	_, err := q.db.Exec(ctx, spoolPayloads, arg.PackIds, arg.Offsets, arg.Datas)
	return err
}

const spooledPayload = `-- name: SpooledPayload :one
SELECT data FROM payload_spool WHERE pack_id = $1 AND "offset" = $2
`

type SpooledPayloadParams struct {
	PackID int64 `json:"pack_id"`
	Offset int32 `json:"offset"`
}

func (q *Queries) SpooledPayload(ctx context.Context, arg SpooledPayloadParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, spooledPayload, arg.PackID, arg.Offset)
	var data []byte
	err := row.Scan(&data)
	return data, err
}
