// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"
	"time"
)

const addProjectUsage = `-- name: AddProjectUsage :one
INSERT INTO project_usage (project_id, day, events) VALUES ($1, $2, $3)
ON CONFLICT (project_id, day) DO UPDATE SET events = project_usage.events + EXCLUDED.events
RETURNING events
`

type AddProjectUsageParams struct {
	ProjectID int64     `json:"project_id"`
	Day       time.Time `json:"day"`
	Events    int64     `json:"events"`
}

// Counts n received events against the project's UTC day and returns the
// day's total (the caller compares it with daily_quota and rolls back).
func (q *Queries) AddProjectUsage(ctx context.Context, arg AddProjectUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, addProjectUsage, arg.ProjectID, arg.Day, arg.Events)
	var events int64
	err := row.Scan(&events)
	return events, err
}

const crashSpikeInputs = `-- name: CrashSpikeInputs :many
WITH recent AS (
    SELECT project_id, count(*) AS n FROM events
    WHERE occurred_at >= $1::timestamptz AND crashcart_is_crash(level, handled)
    GROUP BY project_id),
baseline AS (
    SELECT project_id, sum(crashes) AS n FROM event_stats_hourly
    WHERE bucket >= $2::timestamptz AND bucket < $3::timestamptz
    GROUP BY project_id)
SELECT COALESCE(recent.project_id, baseline.project_id)::bigint AS project_id,
       COALESCE(recent.n, 0)::bigint AS recent, COALESCE(baseline.n, 0)::bigint AS baseline
FROM recent FULL OUTER JOIN baseline USING (project_id)
`

type CrashSpikeInputsParams struct {
	RecentFrom   time.Time `json:"recent_from"`
	BaselineFrom time.Time `json:"baseline_from"`
	BaselineTo   time.Time `json:"baseline_to"`
}

type CrashSpikeInputsRow struct {
	ProjectID int64 `json:"project_id"`
	Recent    int64 `json:"recent"`
	Baseline  int64 `json:"baseline"`
}

// Per project: crashes in the exact last hour (from the raw table, so the
// top of the hour does not matter) vs. the 24 full hourly buckets before
// that hour. Projects with no crashes in either are omitted.
func (q *Queries) CrashSpikeInputs(ctx context.Context, arg CrashSpikeInputsParams) ([]CrashSpikeInputsRow, error) {
	rows, err := q.db.Query(ctx, crashSpikeInputs, arg.RecentFrom, arg.BaselineFrom, arg.BaselineTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrashSpikeInputsRow{}
	for rows.Next() {
		var i CrashSpikeInputsRow
		if err := rows.Scan(&i.ProjectID, &i.Recent, &i.Baseline); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireProjectUsage = `-- name: ExpireProjectUsage :execrows
DELETE FROM project_usage WHERE day < $1
`

func (q *Queries) ExpireProjectUsage(ctx context.Context, day time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expireProjectUsage, day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestReleaseHealth = `-- name: LatestReleaseHealth :one
SELECT e.release,
       COALESCE((SELECT sum(h.total) FROM release_health_daily h
                  WHERE h.project_id = e.project_id AND h.release = e.release
                    AND h.bucket >= $1::timestamptz AND h.bucket < $2::timestamptz), 0)::bigint AS total,
       COALESCE((SELECT sum(h.crashed) FROM release_health_daily h
                  WHERE h.project_id = e.project_id AND h.release = e.release
                    AND h.bucket >= $1::timestamptz AND h.bucket < $2::timestamptz), 0)::bigint AS crashed
FROM crashcart_event_stats($3::bigint, $4::timestamptz, $2::timestamptz, $5::bigint) AS e
WHERE e.release <> ''
GROUP BY e.project_id, e.release
ORDER BY max(e.bucket) DESC, e.release DESC
LIMIT 1
`

type LatestReleaseHealthParams struct {
	DayFrom   time.Time `json:"day_from"`
	ToAt      time.Time `json:"to_at"`
	ProjectID int64     `json:"project_id"`
	HourFrom  time.Time `json:"hour_from"`
	Width     int64     `json:"width"`
}

type LatestReleaseHealthRow struct {
	Release string `json:"release"`
	Total   int64  `json:"total"`
	Crashed int64  `json:"crashed"`
}

// The most recently active release in the window (by events; ties by
// name) with its session totals over the same window (0 without sessions).
// hour_from is the event window start aligned to `width`, day_from the
// day-aligned start for the daily session aggregate.
func (q *Queries) LatestReleaseHealth(ctx context.Context, arg LatestReleaseHealthParams) (LatestReleaseHealthRow, error) {
	row := q.db.QueryRow(ctx, latestReleaseHealth,
		arg.DayFrom,
		arg.ToAt,
		arg.ProjectID,
		arg.HourFrom,
		arg.Width,
	)
	var i LatestReleaseHealthRow
	err := row.Scan(&i.Release, &i.Total, &i.Crashed)
	return i, err
}

const levelTotals = `-- name: LevelTotals :many
SELECT level, sum(events)::bigint AS events
FROM crashcart_event_stats($1::bigint, $2::timestamptz, $3::timestamptz, $4::bigint)
GROUP BY level
`

type LevelTotalsParams struct {
	ProjectID int64     `json:"project_id"`
	FromAt    time.Time `json:"from_at"`
	ToAt      time.Time `json:"to_at"`
	Width     int64     `json:"width"`
}

type LevelTotalsRow struct {
	Level  EventLevel `json:"level"`
	Events int64      `json:"events"`
}

func (q *Queries) LevelTotals(ctx context.Context, arg LevelTotalsParams) ([]LevelTotalsRow, error) {
	rows, err := q.db.Query(ctx, levelTotals,
		arg.ProjectID,
		arg.FromAt,
		arg.ToAt,
		arg.Width,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LevelTotalsRow{}
	for rows.Next() {
		var i LevelTotalsRow
		if err := rows.Scan(&i.Level, &i.Events); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformTotals = `-- name: PlatformTotals :many
SELECT platform, sum(events)::bigint AS events
FROM crashcart_event_stats($1::bigint, $2::timestamptz, $3::timestamptz, $4::bigint)
GROUP BY platform ORDER BY events DESC
`

type PlatformTotalsParams struct {
	ProjectID int64     `json:"project_id"`
	FromAt    time.Time `json:"from_at"`
	ToAt      time.Time `json:"to_at"`
	Width     int64     `json:"width"`
}

type PlatformTotalsRow struct {
	Platform string `json:"platform"`
	Events   int64  `json:"events"`
}

// Raw SDK platforms seen in a window (for the "expected vs received" check).
func (q *Queries) PlatformTotals(ctx context.Context, arg PlatformTotalsParams) ([]PlatformTotalsRow, error) {
	rows, err := q.db.Query(ctx, platformTotals,
		arg.ProjectID,
		arg.FromAt,
		arg.ToAt,
		arg.Width,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformTotalsRow{}
	for rows.Next() {
		var i PlatformTotalsRow
		if err := rows.Scan(&i.Platform, &i.Events); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectUsage = `-- name: ProjectUsage :one
SELECT COALESCE((SELECT events FROM project_usage WHERE project_id = $1 AND day = $2), 0)::bigint
`

type ProjectUsageParams struct {
	ProjectID int64     `json:"project_id"`
	Day       time.Time `json:"day"`
}

func (q *Queries) ProjectUsage(ctx context.Context, arg ProjectUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, projectUsage, arg.ProjectID, arg.Day)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const releaseStats = `-- name: ReleaseStats :many
SELECT s.release,
       COALESCE(r.platforms, '{}'::text[])::text[] AS platforms,
       COALESCE(r.first_seen, min(s.bucket))::timestamptz AS first_seen, max(s.bucket)::timestamptz AS last_seen,
       sum(s.events)::bigint AS events, sum(s.crashes)::bigint AS crashes, sum(s.errors)::bigint AS errors
FROM crashcart_event_stats($1::bigint, $2::timestamptz, $3::timestamptz, $4::bigint) AS s
LEFT JOIN releases r ON r.project_id = s.project_id AND r.release = s.release
WHERE s.release <> ''
GROUP BY s.release, r.platforms, r.first_seen ORDER BY max(s.bucket) DESC, s.release
`

type ReleaseStatsParams struct {
	ProjectID int64     `json:"project_id"`
	FromAt    time.Time `json:"from_at"`
	ToAt      time.Time `json:"to_at"`
	Width     int64     `json:"width"`
}

type ReleaseStatsRow struct {
	Release   string    `json:"release"`
	Platforms []string  `json:"platforms"`
	FirstSeen time.Time `json:"first_seen"`
	LastSeen  time.Time `json:"last_seen"`
	Events    int64     `json:"events"`
	Crashes   int64     `json:"crashes"`
	Errors    int64     `json:"errors"`
}

// Every release with activity in the window, most recently active first;
// platforms and first_seen are all-time, from the releases table.
func (q *Queries) ReleaseStats(ctx context.Context, arg ReleaseStatsParams) ([]ReleaseStatsRow, error) {
	rows, err := q.db.Query(ctx, releaseStats,
		arg.ProjectID,
		arg.FromAt,
		arg.ToAt,
		arg.Width,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseStatsRow{}
	for rows.Next() {
		var i ReleaseStatsRow
		if err := rows.Scan(
			&i.Release,
			&i.Platforms,
			&i.FirstSeen,
			&i.LastSeen,
			&i.Events,
			&i.Crashes,
			&i.Errors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTimeline = `-- name: ReleaseTimeline :many
WITH h AS (
    SELECT crashcart_bucket(bucket, $3::bigint) AS bucket, sum(events) AS events, sum(crashes) AS crashes
    FROM crashcart_event_stats($4::bigint, $1::timestamptz, $2::timestamptz, $3::bigint)
    WHERE release = $5::text
    GROUP BY 1)
SELECT b::timestamptz AS bucket, COALESCE(h.events, 0)::bigint AS events, COALESCE(h.crashes, 0)::bigint AS crashes
FROM crashcart_buckets($1::timestamptz, $2::timestamptz, $3::bigint) AS b
LEFT JOIN h ON h.bucket = b
ORDER BY b
`

type ReleaseTimelineParams struct {
	FromAt    time.Time `json:"from_at"`
	ToAt      time.Time `json:"to_at"`
	Width     int64     `json:"width"`
	ProjectID int64     `json:"project_id"`
	Release   string    `json:"release"`
}

type ReleaseTimelineRow struct {
	Bucket  time.Time `json:"bucket"`
	Events  int64     `json:"events"`
	Crashes int64     `json:"crashes"`
}

func (q *Queries) ReleaseTimeline(ctx context.Context, arg ReleaseTimelineParams) ([]ReleaseTimelineRow, error) {
	rows, err := q.db.Query(ctx, releaseTimeline,
		arg.FromAt,
		arg.ToAt,
		arg.Width,
		arg.ProjectID,
		arg.Release,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReleaseTimelineRow{}
	for rows.Next() {
		var i ReleaseTimelineRow
		if err := rows.Scan(&i.Bucket, &i.Events, &i.Crashes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const timeline = `-- name: Timeline :many

WITH s AS (
    SELECT crashcart_bucket(bucket, $3::bigint) AS bucket, release,
           sum(events) AS events, sum(crashes) AS crashes
    FROM crashcart_event_stats($4::bigint, $1::timestamptz, $2::timestamptz, $3::bigint)
    GROUP BY 1, 2),
ranked AS (
    SELECT release, row_number() OVER (ORDER BY sum(crashes) DESC, sum(events) DESC, release) AS rank
    FROM s GROUP BY release),
series AS (
    SELECT CASE WHEN rank <= $5::bigint THEN release ELSE 'other' END AS series, min(rank) AS rank
    FROM ranked GROUP BY 1),
folded AS (
    SELECT s.bucket, CASE WHEN r.rank <= $5::bigint THEN s.release ELSE 'other' END AS series,
           sum(s.events) AS events, sum(s.crashes) AS crashes
    FROM s JOIN ranked r USING (release) GROUP BY 1, 2)
SELECT b::timestamptz AS bucket, se.series AS release,
       COALESCE(f.events, 0)::bigint AS events, COALESCE(f.crashes, 0)::bigint AS crashes
FROM crashcart_buckets($1::timestamptz, $2::timestamptz, $3::bigint) AS b
CROSS JOIN series se
LEFT JOIN folded f ON f.bucket = b AND f.series = se.series
ORDER BY b, se.rank
`

type TimelineParams struct {
	FromAt    time.Time `json:"from_at"`
	ToAt      time.Time `json:"to_at"`
	Width     int64     `json:"width"`
	ProjectID int64     `json:"project_id"`
	Top       int64     `json:"top"`
}

type TimelineRow struct {
	Bucket  time.Time `json:"bucket"`
	Release string    `json:"release"`
	Events  int64     `json:"events"`
	Crashes int64     `json:"crashes"`
}

// Chart queries take a window [from_at, to_at) (from_at bucket-aligned)
// and a bucket width in seconds. They read crashcart_event_stats (the
// aggregate that matches the width), fold with crashcart_bucket and
// gap-fill with crashcart_buckets, so every bucket of the window comes
// back, in order. The totals take the width for the same reason.
// Events / crashes per bucket, split into the top `top` releases (by
// crashes, then events) plus 'other'; every bucket for every series,
// ordered by bucket, then series rank.
func (q *Queries) Timeline(ctx context.Context, arg TimelineParams) ([]TimelineRow, error) {
	rows, err := q.db.Query(ctx, timeline,
		arg.FromAt,
		arg.ToAt,
		arg.Width,
		arg.ProjectID,
		arg.Top,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimelineRow{}
	for rows.Next() {
		var i TimelineRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Release,
			&i.Events,
			&i.Crashes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totals = `-- name: Totals :one
SELECT COALESCE(sum(events), 0)::bigint AS events,
       COALESCE(sum(crashes), 0)::bigint AS crashes,
       COALESCE(sum(errors), 0)::bigint AS errors
FROM crashcart_event_stats($1::bigint, $2::timestamptz, $3::timestamptz, $4::bigint)
`

type TotalsParams struct {
	ProjectID int64     `json:"project_id"`
	FromAt    time.Time `json:"from_at"`
	ToAt      time.Time `json:"to_at"`
	Width     int64     `json:"width"`
}

type TotalsRow struct {
	Events  int64 `json:"events"`
	Crashes int64 `json:"crashes"`
	Errors  int64 `json:"errors"`
}

func (q *Queries) Totals(ctx context.Context, arg TotalsParams) (TotalsRow, error) {
	row := q.db.QueryRow(ctx, totals,
		arg.ProjectID,
		arg.FromAt,
		arg.ToAt,
		arg.Width,
	)
	var i TotalsRow
	err := row.Scan(&i.Events, &i.Crashes, &i.Errors)
	return i, err
}
