// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: symbols.sql

package sqlc

import (
	"context"
	"time"
)

const getSymbolFileData = `-- name: GetSymbolFileData :one
SELECT data FROM symbol_files WHERE id = $1
`

func (q *Queries) GetSymbolFileData(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSymbolFileData, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const latestSymbolFile = `-- name: LatestSymbolFile :one
SELECT id, platform, release, filename, size, uploaded_at
FROM symbol_files WHERE platform = $1 AND release = $2
ORDER BY uploaded_at DESC LIMIT 1
`

type LatestSymbolFileParams struct {
	Platform string `json:"platform"`
	Release  string `json:"release"`
}

type LatestSymbolFileRow struct {
	ID         int64     `json:"id"`
	Platform   string    `json:"platform"`
	Release    string    `json:"release"`
	Filename   string    `json:"filename"`
	Size       int64     `json:"size"`
	UploadedAt time.Time `json:"uploaded_at"`
}

// Newest upload wins when several files exist for a (platform, release).
func (q *Queries) LatestSymbolFile(ctx context.Context, arg LatestSymbolFileParams) (LatestSymbolFileRow, error) {
	row := q.db.QueryRow(ctx, latestSymbolFile, arg.Platform, arg.Release)
	var i LatestSymbolFileRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Release,
		&i.Filename,
		&i.Size,
		&i.UploadedAt,
	)
	return i, err
}

const listSymbolFiles = `-- name: ListSymbolFiles :many
SELECT id, platform, release, filename, size, uploaded_at
FROM symbol_files ORDER BY platform, release, filename
`

type ListSymbolFilesRow struct {
	ID         int64     `json:"id"`
	Platform   string    `json:"platform"`
	Release    string    `json:"release"`
	Filename   string    `json:"filename"`
	Size       int64     `json:"size"`
	UploadedAt time.Time `json:"uploaded_at"`
}

func (q *Queries) ListSymbolFiles(ctx context.Context) ([]ListSymbolFilesRow, error) {
	rows, err := q.db.Query(ctx, listSymbolFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSymbolFilesRow{}
	for rows.Next() {
		var i ListSymbolFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Release,
			&i.Filename,
			&i.Size,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSymbolFile = `-- name: UpsertSymbolFile :one
INSERT INTO symbol_files (platform, release, filename, size, data)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (platform, release, filename) DO UPDATE SET
    size = EXCLUDED.size, data = EXCLUDED.data, uploaded_at = now()
RETURNING id, platform, release, filename, size, uploaded_at
`

type UpsertSymbolFileParams struct {
	Platform string `json:"platform"`
	Release  string `json:"release"`
	Filename string `json:"filename"`
	Size     int64  `json:"size"`
	Data     []byte `json:"data"`
}

type UpsertSymbolFileRow struct {
	ID         int64     `json:"id"`
	Platform   string    `json:"platform"`
	Release    string    `json:"release"`
	Filename   string    `json:"filename"`
	Size       int64     `json:"size"`
	UploadedAt time.Time `json:"uploaded_at"`
}

func (q *Queries) UpsertSymbolFile(ctx context.Context, arg UpsertSymbolFileParams) (UpsertSymbolFileRow, error) {
	row := q.db.QueryRow(ctx, upsertSymbolFile,
		arg.Platform,
		arg.Release,
		arg.Filename,
		arg.Size,
		arg.Data,
	)
	var i UpsertSymbolFileRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Release,
		&i.Filename,
		&i.Size,
		&i.UploadedAt,
	)
	return i, err
}
