// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: web.sql

package sqlc

import (
	"context"
	"time"

	"github.com/at-least/crashcart/internal/sentry"
)

const issuesIntroducedPerRelease = `-- name: IssuesIntroducedPerRelease :many

SELECT first_release AS release, count(*)::bigint AS n
FROM issues WHERE project_id = $1 AND first_release IS NOT NULL
GROUP BY first_release
`

type IssuesIntroducedPerReleaseRow struct {
	Release *string `json:"release"`
	N       int64   `json:"n"`
}

// Queries used only by the viewer (internal/web).
// How many issues were first seen on each release.
func (q *Queries) IssuesIntroducedPerRelease(ctx context.Context, projectID int64) ([]IssuesIntroducedPerReleaseRow, error) {
	rows, err := q.db.Query(ctx, issuesIntroducedPerRelease, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssuesIntroducedPerReleaseRow{}
	for rows.Next() {
		var i IssuesIntroducedPerReleaseRow
		if err := rows.Scan(&i.Release, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestIssueEvent = `-- name: LatestIssueEvent :one
SELECT occurred_at, project_id, event_id, level, message, platform, environment, release, device_id, device_model, os_version, transaction, error_type, culprit, handled, sdk_name, user_id, fingerprint, symbolicated, tags, symbols, payload FROM events WHERE project_id = $1 AND fingerprint = $2
  AND occurred_at >= $3::timestamptz AND occurred_at < $4::timestamptz
ORDER BY occurred_at DESC LIMIT 1
`

type LatestIssueEventParams struct {
	ProjectID   int64      `json:"project_id"`
	Fingerprint *sentry.ID `json:"fingerprint"`
	FromAt      time.Time  `json:"from_at"`
	ToAt        time.Time  `json:"to_at"`
}

// Bounded to the issue's own [first_seen, last_seen] so only those
// partitions are read (the issue row is the exact range of its events).
func (q *Queries) LatestIssueEvent(ctx context.Context, arg LatestIssueEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, latestIssueEvent,
		arg.ProjectID,
		arg.Fingerprint,
		arg.FromAt,
		arg.ToAt,
	)
	var i Event
	err := row.Scan(
		&i.OccurredAt,
		&i.ProjectID,
		&i.EventID,
		&i.Level,
		&i.Message,
		&i.Platform,
		&i.Environment,
		&i.Release,
		&i.DeviceID,
		&i.DeviceModel,
		&i.OsVersion,
		&i.Transaction,
		&i.ErrorType,
		&i.Culprit,
		&i.Handled,
		&i.SdkName,
		&i.UserID,
		&i.Fingerprint,
		&i.Symbolicated,
		&i.Tags,
		&i.Symbols,
		&i.Payload,
	)
	return i, err
}

const listIssuesIntroducedIn = `-- name: ListIssuesIntroducedIn :many
SELECT project_id, fingerprint, title, level, error_type, transaction, platform, status, status_by, event_count, stored_count, first_seen, last_seen, first_release, last_release, releases, resolved_releases, ignore_until, ignore_until_count, ignore_until_escalating, ignore_baseline, created_at, updated_at FROM issues WHERE project_id = $1 AND first_release = $2
ORDER BY event_count DESC LIMIT $3
`

type ListIssuesIntroducedInParams struct {
	ProjectID    int64   `json:"project_id"`
	FirstRelease *string `json:"first_release"`
	Limit        int32   `json:"limit"`
}

func (q *Queries) ListIssuesIntroducedIn(ctx context.Context, arg ListIssuesIntroducedInParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesIntroducedIn, arg.ProjectID, arg.FirstRelease, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ProjectID,
			&i.Fingerprint,
			&i.Title,
			&i.Level,
			&i.ErrorType,
			&i.Transaction,
			&i.Platform,
			&i.Status,
			&i.StatusBy,
			&i.EventCount,
			&i.StoredCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.FirstRelease,
			&i.LastRelease,
			&i.Releases,
			&i.ResolvedReleases,
			&i.IgnoreUntil,
			&i.IgnoreUntilCount,
			&i.IgnoreUntilEscalating,
			&i.IgnoreBaseline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesPresentIn = `-- name: ListIssuesPresentIn :many
SELECT project_id, fingerprint, title, level, error_type, transaction, platform, status, status_by, event_count, stored_count, first_seen, last_seen, first_release, last_release, releases, resolved_releases, ignore_until, ignore_until_count, ignore_until_escalating, ignore_baseline, created_at, updated_at FROM issues WHERE project_id = $1 AND last_release = $2 AND status NOT IN ('resolved', 'ignored')
ORDER BY event_count DESC LIMIT $3
`

type ListIssuesPresentInParams struct {
	ProjectID   int64   `json:"project_id"`
	LastRelease *string `json:"last_release"`
	Limit       int32   `json:"limit"`
}

// Issues still open whose latest event came from this release.
func (q *Queries) ListIssuesPresentIn(ctx context.Context, arg ListIssuesPresentInParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesPresentIn, arg.ProjectID, arg.LastRelease, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ProjectID,
			&i.Fingerprint,
			&i.Title,
			&i.Level,
			&i.ErrorType,
			&i.Transaction,
			&i.Platform,
			&i.Status,
			&i.StatusBy,
			&i.EventCount,
			&i.StoredCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.FirstRelease,
			&i.LastRelease,
			&i.Releases,
			&i.ResolvedReleases,
			&i.IgnoreUntil,
			&i.IgnoreUntilCount,
			&i.IgnoreUntilEscalating,
			&i.IgnoreBaseline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalLatestReleases = `-- name: PortalLatestReleases :many
SELECT DISTINCT ON (project_id) project_id, release
FROM (SELECT project_id, release, max(bucket) AS last FROM event_stats_hourly
      WHERE bucket >= $1::timestamptz AND bucket < $2::timestamptz AND release <> ''
      GROUP BY 1, 2) t
ORDER BY project_id, last DESC, release DESC
`

type PortalLatestReleasesParams struct {
	FromAt time.Time `json:"from_at"`
	ToAt   time.Time `json:"to_at"`
}

type PortalLatestReleasesRow struct {
	ProjectID int64  `json:"project_id"`
	Release   string `json:"release"`
}

// The most recently active release per project (ties by name, like
// LatestReleaseHealth).
func (q *Queries) PortalLatestReleases(ctx context.Context, arg PortalLatestReleasesParams) ([]PortalLatestReleasesRow, error) {
	rows, err := q.db.Query(ctx, portalLatestReleases, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortalLatestReleasesRow{}
	for rows.Next() {
		var i PortalLatestReleasesRow
		if err := rows.Scan(&i.ProjectID, &i.Release); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalOpenIssues = `-- name: PortalOpenIssues :many
SELECT project_id, count(*)::bigint AS n FROM issues
WHERE status IN ('unresolved', 'regression') GROUP BY 1
`

type PortalOpenIssuesRow struct {
	ProjectID int64 `json:"project_id"`
	N         int64 `json:"n"`
}

func (q *Queries) PortalOpenIssues(ctx context.Context) ([]PortalOpenIssuesRow, error) {
	rows, err := q.db.Query(ctx, portalOpenIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortalOpenIssuesRow{}
	for rows.Next() {
		var i PortalOpenIssuesRow
		if err := rows.Scan(&i.ProjectID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalPlatforms = `-- name: PortalPlatforms :many
SELECT project_id, platform, sum(events)::bigint AS events
FROM event_stats_hourly WHERE bucket >= $1::timestamptz AND bucket < $2::timestamptz
GROUP BY 1, 2 ORDER BY 1, 3 DESC, 2
`

type PortalPlatformsParams struct {
	FromAt time.Time `json:"from_at"`
	ToAt   time.Time `json:"to_at"`
}

type PortalPlatformsRow struct {
	ProjectID int64  `json:"project_id"`
	Platform  string `json:"platform"`
	Events    int64  `json:"events"`
}

// Raw platforms per project in a window, most events first.
func (q *Queries) PortalPlatforms(ctx context.Context, arg PortalPlatformsParams) ([]PortalPlatformsRow, error) {
	rows, err := q.db.Query(ctx, portalPlatforms, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortalPlatformsRow{}
	for rows.Next() {
		var i PortalPlatformsRow
		if err := rows.Scan(&i.ProjectID, &i.Platform, &i.Events); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalReleaseHealth = `-- name: PortalReleaseHealth :many
SELECT k.project_id::bigint AS project_id, COALESCE(sum(h.total), 0)::bigint AS total, COALESCE(sum(h.crashed), 0)::bigint AS crashed
FROM (SELECT unnest($1::bigint[]) AS project_id, unnest($2::text[]) AS release) AS k
JOIN release_health_hourly h ON h.project_id = k.project_id AND h.release = k.release
  AND h.bucket >= $3::timestamptz AND h.bucket < $4::timestamptz
GROUP BY k.project_id
`

type PortalReleaseHealthParams struct {
	ProjectIds []int64   `json:"project_ids"`
	Releases   []string  `json:"releases"`
	FromAt     time.Time `json:"from_at"`
	ToAt       time.Time `json:"to_at"`
}

type PortalReleaseHealthRow struct {
	ProjectID int64 `json:"project_id"`
	Total     int64 `json:"total"`
	Crashed   int64 `json:"crashed"`
}

// Session totals of one release per project (the latest active one).
func (q *Queries) PortalReleaseHealth(ctx context.Context, arg PortalReleaseHealthParams) ([]PortalReleaseHealthRow, error) {
	rows, err := q.db.Query(ctx, portalReleaseHealth,
		arg.ProjectIds,
		arg.Releases,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortalReleaseHealthRow{}
	for rows.Next() {
		var i PortalReleaseHealthRow
		if err := rows.Scan(&i.ProjectID, &i.Total, &i.Crashed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portalUnhandled = `-- name: PortalUnhandled :many

SELECT project_id, sum(unhandled)::bigint AS unhandled
FROM event_stats_hourly WHERE bucket >= $1::timestamptz AND bucket < $2::timestamptz
GROUP BY 1
`

type PortalUnhandledParams struct {
	FromAt time.Time `json:"from_at"`
	ToAt   time.Time `json:"to_at"`
}

type PortalUnhandledRow struct {
	ProjectID int64 `json:"project_id"`
	Unhandled int64 `json:"unhandled"`
}

// The portal: one query per statistic across every project, not four per
// project.
// Unhandled per project in a window (one row per project).
func (q *Queries) PortalUnhandled(ctx context.Context, arg PortalUnhandledParams) ([]PortalUnhandledRow, error) {
	rows, err := q.db.Query(ctx, portalUnhandled, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortalUnhandledRow{}
	for rows.Next() {
		var i PortalUnhandledRow
		if err := rows.Scan(&i.ProjectID, &i.Unhandled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
