// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: web.sql

package sqlc

import (
	"context"

	"github.com/crashcartapp/crashcart/internal/sentry"
)

const issuesIntroducedPerRelease = `-- name: IssuesIntroducedPerRelease :many

SELECT first_release AS release, count(*)::bigint AS n
FROM issues WHERE project_id = $1 AND first_release IS NOT NULL
GROUP BY first_release
`

type IssuesIntroducedPerReleaseRow struct {
	Release *string `json:"release"`
	N       int64   `json:"n"`
}

// Queries used only by the viewer (internal/web).
// How many issues were first seen on each release.
func (q *Queries) IssuesIntroducedPerRelease(ctx context.Context, projectID int64) ([]IssuesIntroducedPerReleaseRow, error) {
	rows, err := q.db.Query(ctx, issuesIntroducedPerRelease, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssuesIntroducedPerReleaseRow{}
	for rows.Next() {
		var i IssuesIntroducedPerReleaseRow
		if err := rows.Scan(&i.Release, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestIssueEvent = `-- name: LatestIssueEvent :one
SELECT occurred_at, project_id, event_id, level, message, platform, environment, release, device_id, device_model, os_version, screen, error_type, error_location, handled, sdk_name, user_id, fingerprint, symbolicated, tags, payload, symbols FROM events WHERE project_id = $1 AND fingerprint = $2 ORDER BY occurred_at DESC LIMIT 1
`

type LatestIssueEventParams struct {
	ProjectID   int64      `json:"project_id"`
	Fingerprint *sentry.ID `json:"fingerprint"`
}

func (q *Queries) LatestIssueEvent(ctx context.Context, arg LatestIssueEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, latestIssueEvent, arg.ProjectID, arg.Fingerprint)
	var i Event
	err := row.Scan(
		&i.OccurredAt,
		&i.ProjectID,
		&i.EventID,
		&i.Level,
		&i.Message,
		&i.Platform,
		&i.Environment,
		&i.Release,
		&i.DeviceID,
		&i.DeviceModel,
		&i.OsVersion,
		&i.Screen,
		&i.ErrorType,
		&i.ErrorLocation,
		&i.Handled,
		&i.SdkName,
		&i.UserID,
		&i.Fingerprint,
		&i.Symbolicated,
		&i.Tags,
		&i.Payload,
		&i.Symbols,
	)
	return i, err
}

const listIssuesIntroducedIn = `-- name: ListIssuesIntroducedIn :many
SELECT project_id, fingerprint, title, level, error_type, screen, platform, status, event_count, stored_count, first_seen, last_seen, first_release, last_release, resolved_release, created_at, updated_at FROM issues WHERE project_id = $1 AND first_release = $2
ORDER BY event_count DESC LIMIT $3
`

type ListIssuesIntroducedInParams struct {
	ProjectID    int64   `json:"project_id"`
	FirstRelease *string `json:"first_release"`
	Limit        int32   `json:"limit"`
}

func (q *Queries) ListIssuesIntroducedIn(ctx context.Context, arg ListIssuesIntroducedInParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesIntroducedIn, arg.ProjectID, arg.FirstRelease, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ProjectID,
			&i.Fingerprint,
			&i.Title,
			&i.Level,
			&i.ErrorType,
			&i.Screen,
			&i.Platform,
			&i.Status,
			&i.EventCount,
			&i.StoredCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.FirstRelease,
			&i.LastRelease,
			&i.ResolvedRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesPresentIn = `-- name: ListIssuesPresentIn :many
SELECT project_id, fingerprint, title, level, error_type, screen, platform, status, event_count, stored_count, first_seen, last_seen, first_release, last_release, resolved_release, created_at, updated_at FROM issues WHERE project_id = $1 AND last_release = $2 AND status NOT IN ('resolved', 'ignored')
ORDER BY event_count DESC LIMIT $3
`

type ListIssuesPresentInParams struct {
	ProjectID   int64   `json:"project_id"`
	LastRelease *string `json:"last_release"`
	Limit       int32   `json:"limit"`
}

// Issues still open whose latest event came from this release.
func (q *Queries) ListIssuesPresentIn(ctx context.Context, arg ListIssuesPresentInParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesPresentIn, arg.ProjectID, arg.LastRelease, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ProjectID,
			&i.Fingerprint,
			&i.Title,
			&i.Level,
			&i.ErrorType,
			&i.Screen,
			&i.Platform,
			&i.Status,
			&i.EventCount,
			&i.StoredCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.FirstRelease,
			&i.LastRelease,
			&i.ResolvedRelease,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestIssueEvent = `-- name: OldestIssueEvent :one
SELECT occurred_at, project_id, event_id, level, message, platform, environment, release, device_id, device_model, os_version, screen, error_type, error_location, handled, sdk_name, user_id, fingerprint, symbolicated, tags, payload, symbols FROM events WHERE project_id = $1 AND fingerprint = $2 ORDER BY occurred_at ASC LIMIT 1
`

type OldestIssueEventParams struct {
	ProjectID   int64      `json:"project_id"`
	Fingerprint *sentry.ID `json:"fingerprint"`
}

func (q *Queries) OldestIssueEvent(ctx context.Context, arg OldestIssueEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, oldestIssueEvent, arg.ProjectID, arg.Fingerprint)
	var i Event
	err := row.Scan(
		&i.OccurredAt,
		&i.ProjectID,
		&i.EventID,
		&i.Level,
		&i.Message,
		&i.Platform,
		&i.Environment,
		&i.Release,
		&i.DeviceID,
		&i.DeviceModel,
		&i.OsVersion,
		&i.Screen,
		&i.ErrorType,
		&i.ErrorLocation,
		&i.Handled,
		&i.SdkName,
		&i.UserID,
		&i.Fingerprint,
		&i.Symbolicated,
		&i.Tags,
		&i.Payload,
		&i.Symbols,
	)
	return i, err
}
