// Package blob is the optional object store for symbol files: whole
// objects in, whole objects out, keyed by strings the caller generates.
// Postgres remains the default location (no Store configured — the bytes
// stay in symbol_files.data); FS and S3 are the alternatives, chosen by
// BLOB_STORE. The interface is deliberately small: symbol files are
// written once, read rarely and never queried by content.
package blob

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
)

// ErrNotFound: no object at that key.
var ErrNotFound = errors.New("blob not found")

// Store is the object store. Delete of a missing key is not an error.
type Store interface {
	Put(ctx context.Context, key string, data []byte) error
	Get(ctx context.Context, key string) ([]byte, error)
	Delete(ctx context.Context, key string) error
}

// SymbolKey is a fresh key for one symbol file of a project:
// symbols/<projectID>/<random>. Random, not content-addressed, so two rows
// never share a key and deleting one can never take the other's bytes —
// and a re-upload is a new key, never an in-place overwrite.
func SymbolKey(projectID int64) string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err) // crypto/rand failing is not a condition to continue under
	}
	return fmt.Sprintf("symbols/%d/%s", projectID, hex.EncodeToString(b[:]))
}

// checkKey refuses keys FS could not store safely and S3 would mangle:
// empty, absolute, or with a "." / ".." element. Keys are generated by
// SymbolKey, so this is a guard, not input validation.
func checkKey(key string) error {
	if key == "" || strings.HasPrefix(key, "/") {
		return fmt.Errorf("blob: invalid key %q", key)
	}
	for _, el := range strings.Split(key, "/") {
		if el == "" || el == "." || el == ".." {
			return fmt.Errorf("blob: invalid key %q", key)
		}
	}
	return nil
}
