// Package blob is the optional object store (BLOB_STORE=s3) for symbol
// files and event payloads: whole objects in, whole objects or ranges
// out, keyed by strings the caller generates. Postgres remains the
// default (no Store configured — bytes stay in their tables). The
// interface is deliberately small: these bytes are written once, read
// rarely and never queried by content.
package blob

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
	"time"
)

// ErrNotFound: no object at that key.
var ErrNotFound = errors.New("blob not found")

// Store is the object store. Delete of a missing key is not an error;
// GetRange reads n bytes from off (a payload out of a pack) and is
// ErrNotFound for a missing key like Get.
type Store interface {
	Put(ctx context.Context, key string, data []byte) error
	Get(ctx context.Context, key string) ([]byte, error)
	GetRange(ctx context.Context, key string, off, n int64) ([]byte, error)
	Delete(ctx context.Context, key string) error
}

// PackKey names one pack of a project's events for a week (retention's
// Monday-aligned week, so a week's packs share a prefix that goes with
// its partition).
func PackKey(projectID int64, week time.Time, packID int64) string {
	return fmt.Sprintf("events/%d/%s/%d", projectID, week.UTC().Format("20060102"), packID)
}

// SymbolKey is a fresh key for one symbol file of a project:
// symbols/<projectID>/<random>. Random, not content-addressed, so two rows
// never share a key and deleting one can never take the other's bytes —
// and a re-upload is a new key, never an in-place overwrite.
func SymbolKey(projectID int64) string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic(err) // crypto/rand failing is not a condition to continue under
	}
	return fmt.Sprintf("symbols/%d/%s", projectID, hex.EncodeToString(b[:]))
}

// checkKey refuses keys a store would mangle: empty, absolute, or with a
// "." / ".." element. Keys are generated by SymbolKey / PackKey, so this
// is a guard, not input validation.
func checkKey(key string) error {
	if key == "" || strings.HasPrefix(key, "/") {
		return fmt.Errorf("blob: invalid key %q", key)
	}
	for _, el := range strings.Split(key, "/") {
		if el == "" || el == "." || el == ".." {
			return fmt.Errorf("blob: invalid key %q", key)
		}
	}
	return nil
}
